🔀 :: register all view
team-aliens/DMS-Android pull request #109
Opened 2022-11-10 13:18 UTC by Leesin0222

## 개요
>회원가입 모든 화면을 구현합니다.

## 작업사항
- 회원가입 모든화면(프로필 사진, 약관동의, 아이디 설정, 비밀번호 설정, 이메일 주소 입력, 이메일 인증, 학교 코드 입력 학교 인증)

### View
<p align = "center">
<img src="https://user-images.githubusercontent.com/90879448/201088178-58421139-68bd-4e3a-ac3e-f4bc894e61e0.png"  width="180" height="320"/>
<img src="https://user-images.githubusercontent.com/90879448/201088725-d810b38a-2039-4e9a-809b-a0f85575fbb1.png"  width="180" height="320"/>
<img src="https://user-images.githubusercontent.com/90879448/201089169-d3596513-b40e-4055-9a82-d3bfb7070d61.png"  width="180" height="320"/>
<img src="https://user-images.githubusercontent.com/90879448/201089601-62cbe0d9-5ae2-4b8b-8070-692bc09c6e85.png"  width="180" height="320"/>
<img src="https://user-images.githubusercontent.com/90879448/201091236-755beffd-ee36-451e-a94d-7d88c9fe40aa.png"  width="180" height="320"/>
<img src="https://user-images.githubusercontent.com/90879448/201101119-6dc20ac3-1464-440a-8d60-2ec130d6bb8a.png"  width="180" height="320"/>
<img src="https://user-images.githubusercontent.com/90879448/201101530-040bd9dd-93cb-4c6c-98d1-a8aa8bcd5561.png"  width="180" height="320"/>
<img src="https://user-images.githubusercontent.com/90879448/201101892-aade4a75-162d-4eb9-ae53-ad36d744fc60.png"  width="180" height="320"/>
</p>

## 추가 로 할 말
PR단위 좀 크게 잡음 쏘리

2022-11-12 07:30 UTC, aahspringaa4 requested changes
이건 전체적인 리뷴데 0.444444 0.955555하지 말고 걍 margin horizontal하세요
이걸 왜 궂이 이렇게 하는지 이해가 안가네요.. 쓸모없는 가이드 라인이잖아요. XML은 잘하시는 줄 알았는데 정말 여러모로 실망이네요.

2022-11-12 07:30 UTC, aahspringaa4 commented on presentation/build.gradle.kts
> +        viewBinding = true
ViewBinding은 궂이 추가 왜해주는건가여? 다 DataBinding으로 될텐데 (8/10)

2022-11-12 07:30 UTC, aahspringaa4 commented on presentation/src/main/java/com/example/dms_android/customui/RegisterCustomButton.kt
> +@SuppressLint("ResourceType")
ResourceType은 이제 곧 서비스 종료될 라이브러리니까 다른 방법 찾아보시는게 좋을것같아요. 정힘들면 어쩔 수 없고 리뷰 반영 급한정도 (6/10)

2022-11-12 07:30 UTC, aahspringaa4 commented on presentation/src/main/java/com/example/dms_android/customui/RegisterCustomButton.kt
> +            }
뭐하는 코드인지는 모르겠지만 스트링 리소스나 변수들로 추측해봤을땐 그렇게 좋은 코드는 아닌 것같아요. (4/10)

2022-11-12 07:30 UTC, aahspringaa4 commented on presentation/src/main/java/com/example/dms_android/customui/RegisterCustomButton.kt
> +            setMainText(typedArr.getString(R.styleable.RegisterCustomButton_first_text) ?: "값없음")
값없음이 뭐하는 애인지는 모르겠지만 String Resource로 빼주세여 (10/10)

2022-11-12 07:30 UTC, aahspringaa4 commented on presentation/src/main/res/layout/activity_email_certification.xml
> +        android:layout_marginEnd="56dp"
Start End 하나하나 보다는 marginHorizontal 하시면 동시에 들어가요 (9/10)

2022-11-12 07:30 UTC, aahspringaa4 commented on presentation/src/main/res/layout/activity_email_certification.xml
> +        android:text="dms logo"
제가 임시로 만들어둔 지금 DMS로고 있거든요? 그거 임시로 넣는게 좋을것같아요 아무래도 정사각형인데 이건 직사각형이니까 비율 맞춰보려면

2022-11-12 07:30 UTC, aahspringaa4 commented on presentation/src/main/res/layout/activity_policy.xml
> +            android:text="dms logo"
여기도 DMS 현재로고로 임시로 넣어주세여 (8/10)

2022-11-12 07:30 UTC, aahspringaa4 commented on presentation/src/main/res/layout/activity_school_certification.xml
> +        android:text="dms logo"
여기도 현재 로고 (8/10)

2022-11-12 07:30 UTC, aahspringaa4 commented on presentation/src/main/res/layout/activity_school_certification.xml
> +        android:layout_marginEnd="30dp"
여기도 marginHorizontal (9/10)

2022-11-12 07:30 UTC, aahspringaa4 commented on presentation/src/main/res/layout/activity_set_id.xml
> +            android:text="dms logo"
여기도 지금 로고

2022-11-12 07:30 UTC, aahspringaa4 commented on presentation/src/main/res/layout/activity_set_password.xml
> +            android:layout_marginTop="37dp"
여기도

2022-11-12 07:31 UTC, aahspringaa4 commented
코드 리뷰는 전체적인 코드 스타일만 리뷰했습니다. 하나하나 비율이나 padding 도 리뷰하고 싶은데 전 시간이 없어서.. 솔찍히 지금 하는거 보면 다 해야하는데 워낙 리뷰해야할 양이 많고 시간도 없으니 용진님 믿겠습니다.

2022-11-12 09:36 UTC, Leesin0222 commented on presentation/build.gradle.kts
> +        viewBinding = true
커스텀 뷰 만드는데 씀

2022-11-12 09:36 UTC, Leesin0222 commented on presentation/src/main/java/com/example/dms_android/customui/RegisterCustomButton.kt
> +@SuppressLint("ResourceType")
교체 함

2022-11-12 10:11 UTC, Leesin0222 commented on presentation/src/main/java/com/example/dms_android/customui/RegisterCustomButton.kt
> +            }
..?

2022-11-12 10:29 UTC, limsaehyun commented on buildSrc/src/main/kotlin/Dependency.kt
> +    object PinEntryEditText {
EntryEditText 사용 대신 앱 내에서 `커스텀` 할 수 있도록 만들면 좋겠다는 생각이 들어요.
그래서 디자인 시스템으로 얻을 수 있는 이점(컴포넌트 중복 방지, 일관된 디자인, 컴포넌트 빠른 대응)
등등을 얻을 수 있어서요. (추가적으로 완벽하게 커스텀이 불가능하단 점도 있구요)
우선 시간이 없다면 임시 방편으로 할 수 있겠지만,
추후에 변경할 수 있는 구조를 부탁드려요!
(앱 내에 TODO도 박아주시면 좋구요)

2022-11-12 10:29 UTC, limsaehyun commented on presentation/src/main/java/com/example/dms_android/customui/RegisterCustomButton.kt
> +            }
전 이런 코드 스타일은 괜찮다고 생각해요. 다만
getString에서 값 없음 보다는 `""`  를 주어 empty 상태라는걸 `도메인적 의미`를 표현해주었으면 해요

2022-11-12 10:29 UTC, limsaehyun commented on presentation/src/main/res/drawable/ic_eyes_off.xml
> +<vector xmlns:android="http://schemas.android.com/apk/res/android"
해당 아이콘은 디자인 시스템에 이미 존재합니다!

2022-11-12 10:29 UTC, limsaehyun commented on presentation/src/main/res/layout/activity_confirm_school.xml
> +            android:id="@+id/imageView"
View 네이밍에 신경써주세요.
추후 가독성을 위해
이게 어떤 View인지를 할 수 있는 네이밍을 부탁드려요
ex) `tvMainTitle`
네이밍 컨벤션에 관해서는 한 번 회의를 통해 바로잡으면 좋겠네요.

2022-11-12 10:29 UTC, limsaehyun commented on presentation/src/main/res/values/strings.xml
> +    <string name="ResendVerificationCode"><u>인증코드 재발송</u></string>
일관된 네이밍을 사용해주세요.
현재 string의 id는 스네이크 케이스와 카멜 케이스가 혼합된 형태에요.
이 부분은 가독성에 좋지 않다고 생각해요
이 `스타일은 하나로 통일`하면 좋을 것 같아요.

2022-11-13 02:18 UTC, Leesin0222 commented on presentation/src/main/res/values/strings.xml
> +    <string name="ResendVerificationCode"><u>인증코드 재발송</u></string>
전에도 인지하고는 있었지만 저걸 쓰는 다른 부분이 있기 때문에 이 PR에서 해결하기엔 너무 상관 없는 PR인 것 같아서 새로 PR하나 파서 수정하겠습다.

2022-11-13 02:22 UTC, Leesin0222 commented on buildSrc/src/main/kotlin/Dependency.kt
> +    object PinEntryEditText {
알겠습니다!

2022-11-13 02:35 UTC, Leesin0222 commented on presentation/src/main/res/layout/activity_confirm_school.xml
> +            android:id="@+id/imageView"
수정했습니다!

2022-11-13 02:44 UTC, Leesin0222 commented on buildSrc/src/main/kotlin/Dependency.kt
> +    object PinEntryEditText {
TODO 처리 해놓았습니다!

2022-11-13 03:23 UTC, aahspringaa4 commented
제가 커밋 단위 크게 파라고 얼마나 말씀드렸는데.. 리뷰 반영이면 한꺼면에 "♻️ :: Review Refactor" 하라고요.. 그리고 영어로만 하라고 얼마나 말씀드렸는데,,

2022-11-13 03:26 UTC, aahspringaa4 approved these changes
수고하셨습니다. 하지만 앞으로는 해당 사안들은 지켜주시길 바랍니다.

1. 이슈 단위는 작게 (리뷰 하기 편하고 리뷰가 편해야 빨리 머지됨)
2. 커밋 단위는 크게 (커밋 단위가 너무 작아요 파일 체인지가 20개인데 커밋이 30개이것도 말이 안되요. 기능 별로 딱딱 묶어서 커밋해주세요. 리뷰 반영도 한번에 해주시고요)
3. 커밋 메세지는 영어로 하기로 한거니까 영어로 작성해주세요.
4. 개발 속도가 너무 느려요. 어려운 내용 아니니까 개발 속도좀 높여주세요.

2022-11-13 05:12 UTC, merged

2022-11-13 05:13 UTC, Leesin0222 commented
> 수고하셨습니다. 하지만 앞으로는 해당 사안들은 지켜주시길 바랍니다.
> 
> 1. 이슈 단위는 작게 (리뷰 하기 편하고 리뷰가 편해야 빨리 머지됨)
> 2. 커밋 단위는 크게 (커밋 단위가 너무 작아요 파일 체인지가 20개인데 커밋이 30개이것도 말이 안되요. 기능 별로 딱딱 묶어서 커밋해주세요. 리뷰 반영도 한번에 해주시고요)
> 3. 커밋 메세지는 영어로 하기로 한거니까 영어로 작성해주세요.
> 4. 개발 속도가 너무 느려요. 어려운 내용 아니니까 개발 속도좀 높여주세요.

YES