Feature/117 modifier register school viewmodel implementation register school fragment
team-aliens/DMS-Android pull request #127
Opened 2022-11-20 09:20 UTC by Leesin0222

## 개요
> 학교 인증코드 입력, 학교 확인 질문을 구현합니다.

## 작업사항
- SchoolCertificationScreen.kt : xml이라서 이미 구현한 Compose View 주석처리
- LifeCycle.kt : repeatOnLifeCycle이용하여 LifeCycle함수 맹들어주기
- ExamineSchoolCodeEvent.kt : 기존의 InputSchoolCode라는 이벤트 제거(xml사용으로 인하여)
- ExamineSchoolCodeViewModel.kt : 학교 인증 코드 검사 ViewModel 작성
- fragment_school_certification.xml : 시간 뷰 삭제 및 backgroundColor White로 지정(안 그러면 뒤에 Activity가 비춰보이기 때문), PinCodeView 해상도 땜에 일부 기기에서 잘려보이는 현상 해결
- ConfirmSchoolScreen.kt : xml이라서 이미 구현한 Compose View 주석처리
- ConfirmSchoolEvent.kt : 학교 확인 Event 작성
- fragment_confirm_school.xml : 학교 확인 뷰에 errorTextView 추가
- View.kt : Visibility 관련 Extension  작성
- register_et_error_background.xml : 회원가입 error EditText BackGround 작성
- strings.xml : 학교 답변 비교 NotFound String 수정
-  ConfirmSchoolState.kt : state 작성
-  SchoolCertificationFragment.kt : 학교 인증코드 입력 Fragment 작성
- ConfirmSchoolViewModel.kt : 학교 확인 ViewModel 작성 
- ConfirmSchoolFragment.kt :  학교 확인 Fragment 작성
- Dependency,kt : FRAGMENT_KTX_NEW Dependency 작성
- Versions.kt : FRAGMENT_KTX_NEW Version 작성
- build.gradle.kts : fragment_ktx_new presentation에 추가함으로써 에러 제거
- register_custom_active_btn_background : 버튼 활성화 drawable 작성
- 
### 파일을 제거함
 SchoolQuestionViewModel.kt, CompareSchoolAnswerViewModel.kt, SchoolQuestionEvent.kt, CompareSchoolAnswerEvent.kt, CompareSchoolAnswerState.kt : viewModel 합침으로 인하여 제거 

## 추가로 할 말
아직 Flow에 대한 지식 미숙으로 임시로 LiveData를 사용하게 되었습니다 . 추후에 Flow로 변경할 예정이고 TODO 박아놓았습니다.

2022-11-20 10:55 UTC, limsaehyun commented
branch이름과 PR Title이 너무 길어요. 간략하게 작성 부탁드립니다.

2022-11-20 10:57 UTC, Leesin0222 commented
> branch이름과 PR Title이 너무 길어요. 간략하게 작성 부탁드립니다.

넵

2022-11-20 14:00 UTC, aahspringaa4 requested changes
말도 안하고 LiveData 사용하시고 Todo 박는건 좀 어이가 없네여;; 애초에 eventFlow는 워크허브에서 쓰셨어서 이걸 어려워하실 이유가 없으실것같은데 궂이 이렇게 하시는건 이해가 안가네요. 예시 코드도 다 있는데,
코드 전체적으로 맞는 코드인지도 모르겠네요.

2022-11-20 14:06 UTC, aahspringaa4 commented on presentation/src/main/java/com/example/dms_android/feature/register/screen/school/ConfirmSchoolScreen.kt
> +}*/
주석하지 마시고 안쓰실꺼면 지우시는게 나을것같아요.

2022-11-20 15:25 UTC, Leesin0222 commented on presentation/src/main/java/com/example/dms_android/feature/register/screen/school/ConfirmSchoolScreen.kt
> +}*/
추후에 jetpack compose로 마이그레이션 해야 할 수 있기 때문에 일단 주석처리 해놓는게 현명하다고 생각했습니다.

2022-11-20 23:50 UTC, limsaehyun commented on presentation/src/main/java/com/example/dms_android/feature/register/event/school/ConfirmSchoolEvent.kt
> +    object SchoolQuestionSuccess : ConfirmSchoolEvent()
해당 이벤트 이름은 SideEffect이름으로는 부적합한 것 같습니다.
구체적으로 어떠한 이벤트인지 명시해줘야 할 것 같네요.

2022-11-20 23:50 UTC, limsaehyun commented on presentation/src/main/java/com/example/dms_android/feature/register/screen/school/ConfirmSchoolScreen.kt
> +}*/
TODO처리 해주시면 될 것 같네요

2022-11-20 23:50 UTC, limsaehyun commented on presentation/src/main/java/com/example/dms_android/feature/register/screen/school/SchoolCertificationCodeScreen.kt
> +/*private var onBtnActive = false
여기도 TODO를 구체적으로 작성해주세요

2022-11-20 23:50 UTC, limsaehyun commented on presentation/src/main/java/com/example/dms_android/feature/register/ui/school/ConfirmSchoolFragment.kt
> +                binding.tvError.text = R.string.BadRequest.toString()
`string resource`를 toString으로 처리하면 값이 정상적으로 반환 안되지 않나요?

2022-11-20 23:52 UTC, limsaehyun commented on presentation/src/main/java/com/example/dms_android/feature/register/ui/school/ConfirmSchoolFragment.kt
> +                binding.tvError.text = R.string.inconsistent_school_reply.toString()
https://github.com/team-aliens/DMS-Android/pull/127#discussion_r1027377112

2022-11-20 23:52 UTC, limsaehyun commented on presentation/src/main/java/com/example/dms_android/feature/register/ui/school/ConfirmSchoolFragment.kt
> +            is ConfirmSchoolEvent.CompareSchoolNotFound -> {
https://github.com/team-aliens/DMS-Android/pull/127#discussion_r1027377112

2022-11-21 00:25 UTC, aahspringaa4 commented on presentation/src/main/java/com/example/dms_android/feature/register/screen/school/ConfirmSchoolScreen.kt
> +}*/
마이그레이션을해도 그때가서 추가하면 되죠. 왜 지금 TODO를 박는거에요.

2022-11-24 00:01 UTC, aahspringaa4 approved these changes
수고하셨습니다.

2022-11-24 00:14 UTC, merged