🔀 :: (#) implement id settings
team-aliens/DMS-Android pull request #130
Opened 2022-11-20 14:51 UTC by Leesin0222

## 개요
> 아이디 세팅 viewmodelm, fragment를 구현합니다.

## 작업사항
- todo

## 추가 로 할 말

2022-12-06 11:07 UTC, limsaehyun commented on presentation/src/main/java/com/example/dms_android/feature/MainActivity.kt
> +            4 -> {
Index는 Enum이나 가독성 좋은 방식으로 바꿔주세요

2022-12-06 11:07 UTC, limsaehyun commented on presentation/src/main/java/com/example/dms_android/feature/register/ui/id/SetIdFragment.kt
> +    private var a = false
변수명 가독성을 올려주세요

2022-12-06 11:07 UTC, limsaehyun commented on presentation/src/main/java/com/example/dms_android/feature/register/ui/id/SetIdFragment.kt
> +            binding.etClass.isClickable = false
로직.. 개편 부탁드립니다

2022-12-14 00:02 UTC, Leesin0222 commented on presentation/src/main/java/com/example/dms_android/feature/MainActivity.kt
> +            4 -> {
딴 pr... i want it

2022-12-14 00:02 UTC, Leesin0222 commented on presentation/src/main/java/com/example/dms_android/feature/register/ui/id/SetIdFragment.kt
> +    private var a = false
해결 완!

2022-12-14 00:02 UTC, Leesin0222 commented on presentation/src/main/java/com/example/dms_android/feature/register/ui/id/SetIdFragment.kt
> +            binding.etClass.isClickable = false
급한 것 먼저 해결하고 리팩토링 하겠습니다.

2022-12-14 01:03 UTC, aahspringaa4 requested changes

2022-12-14 01:03 UTC, aahspringaa4 commented on presentation/src/main/java/com/example/dms_android/feature/register/ui/email/EmailCertificationFragment.kt
> +                vm.authCode = temp.toString()
temp에 값이 이미  .toString해서 이 형태로 들어오는데 여기서 굳이 .toString을 한번 더 해준 이유가 무엇인가요

2022-12-14 01:03 UTC, aahspringaa4 commented on presentation/src/main/java/com/example/dms_android/viewmodel/auth/register/id/SetIdViewModel.kt
> +        TODO("Not yet implemented")
TODO 이렇게 있으면 컴파일 에러 날텐데 실행 시켜보고 올리는거 맞나여?

2022-12-14 01:03 UTC, aahspringaa4 commented on presentation/src/main/java/com/example/dms_android/feature/register/ui/id/SetIdFragment.kt
> +            binding.etClass.isClickable = false
이거는 지금 당장하라고는 안하겠는데 무조건 로직 개편 해주셔야할것같아요.

2022-12-14 01:03 UTC, aahspringaa4 commented on presentation/src/main/java/com/example/dms_android/feature/register/ui/id/SetIdFragment.kt
> +                binding.tvRealName.text = "${vm.name}님이 맞습니까?"
Activity에서 Model안거치고 바로 ViewModel을 관찰하는건 좋지 않은 코드인것 같아요. 원랜 이런걸 State로 추상화하라고 한건데..

2022-12-14 01:09 UTC, Leesin0222 commented on presentation/src/main/java/com/example/dms_android/feature/register/ui/email/EmailCertificationFragment.kt
> +                vm.authCode = temp.toString()
![image](https://user-images.githubusercontent.com/90879448/207480054-c846fdea-593c-436c-a8ff-286e839391da.png)
붙히지 않으면 이런 에러가 발생하게 됩니다.

2022-12-14 08:30 UTC, Leesin0222 commented on presentation/src/main/java/com/example/dms_android/viewmodel/auth/register/id/SetIdViewModel.kt
> +        TODO("Not yet implemented")
실행되서 올렸습니다.

2022-12-24 12:24 UTC, Leesin0222 commented on presentation/src/main/java/com/example/dms_android/feature/register/event/id/SetIdEvent.kt
> +    object DuplicateIdConflict : SetIdEvent()
해결 완!

2022-12-24 12:25 UTC, Leesin0222 commented on presentation/src/main/java/com/example/dms_android/feature/register/event/id/SetIdEvent.kt
> +    data class ErrorMessage(val message: String) : SetIdEvent()
해결 완!

2022-12-24 12:25 UTC, Leesin0222 commented on presentation/src/main/java/com/example/dms_android/feature/register/ui/email/EmailCertificationFragment.kt
> +                vm.authCode = temp.toString()
해결 완!

2022-12-24 12:29 UTC, merged