🔀 :: (#141) Cafeteria View
team-aliens/DMS-Android pull request #144
Opened 2022-12-14 07:42 UTC by aahspringaa4

## 개요
급식 뷰의 완성되지 않은 뷰를 Compose로 완성하였습니다.

## 작업사항
2차 스프린트 뷰 작업 완료

## 추가 로 할 말

2022-12-14 08:21 UTC, limsaehyun requested changes
수고하셨습니다.
변경이 필요한 부분이 몇가지 있어 Request changes 걸어두었습니다.
그리고, UI 사진 첨부해주시면 감사하겠습니다!

2022-12-14 08:21 UTC, limsaehyun commented on design-system/src/main/java/com/example/design_system/color/colors.kt
> +    val ErrorLighten100 = Color(color = 0x14FF4646)
네이밍 가독성이 떨어져요.
`LightenError` 정도가 적당하겠네요.

2022-12-14 08:21 UTC, limsaehyun commented on local_database/src/main/java/com/example/local_database/entity/meal/MealRoomEntity.kt
> +fun MealRoomEntity.toEntity() =
특정 모듈에서만 쓰이는 extension은 `internal` 처리 부탁드려요

2022-12-14 08:21 UTC, limsaehyun commented on presentation/build.gradle.kts
> +    implementation("androidx.compose.ui:ui-util:${Versions.COMPOSE}")
implementation은 `buildSrc`에서 관리해주세요.

2022-12-14 08:21 UTC, limsaehyun commented on presentation/src/main/java/com/example/dms_android/feature/HomeActivity.kt
> +import android.util.Log
필요없는 `import 제거`해주세요.

2022-12-14 08:21 UTC, limsaehyun commented on presentation/src/main/java/com/example/dms_android/feature/MainActivity.kt
> +import android.util.Log
필없지

2022-12-14 08:21 UTC, limsaehyun commented on presentation/src/main/java/com/example/dms_android/feature/home/CafeteriaFragment.kt
> +class CafeteriaFragment : BaseFragment<FragmentHomeBinding>(
필요없는 Fragment는 `제거`해주세요.

2022-12-14 08:21 UTC, limsaehyun commented on presentation/src/main/java/com/example/dms_android/feature/home/MealContent.kt
> +                    0 -> {
추후에 작업에 필요한 사항은 TODO 처리 부탁드려요

2022-12-14 08:21 UTC, limsaehyun commented on presentation/src/main/java/com/example/dms_android/feature/home/PagerMarginItemDecoration.kt
> +class PagerMarginItemDecoration(context: Fragment, @DimenRes horizontalMargin: Int) :
이 친구는 어디에서 쓰이나요?

2022-12-14 08:21 UTC, limsaehyun commented on presentation/src/main/java/com/example/dms_android/feature/home/adapter/MealPagerAdapter.kt
> +        init {
`dataBinding` 처리 해주세요.
findViewById는 지양해주세요.

2022-12-14 08:21 UTC, limsaehyun commented on presentation/src/main/java/com/example/dms_android/feature/mypage/MyPageEvent.kt
> +    object UnAuthorizedException: MyPageEvent()
Event은 특정 동작을 의미하도록 네이밍하는 것을 권장드립니다.

2022-12-14 08:21 UTC, limsaehyun commented on presentation/src/main/java/com/example/dms_android/viewmodel/mypage/MyPageViewModel.kt
> +class MyPageViewModel @Inject constructor(
ViewModel 을 Injection하기 위한
@HiltViewModel 어노테이션이 존재하지 않습니다.
혹시 동작 확인 하셨나요?

2022-12-14 09:59 UTC, aahspringaa4 commented on presentation/src/main/java/com/example/dms_android/viewmodel/mypage/MyPageViewModel.kt
> +class MyPageViewModel @Inject constructor(
했는데 저 뷰모델이 사용이 안되서 에러가 안난것 같아요. 추가하겠습니다.

2022-12-15 05:51 UTC, aahspringaa4 commented on presentation/src/main/java/com/example/dms_android/feature/home/PagerMarginItemDecoration.kt
> +class PagerMarginItemDecoration(context: Fragment, @DimenRes horizontalMargin: Int) :
삭제 완료

2022-12-15 05:52 UTC, aahspringaa4 commented on presentation/src/main/java/com/example/dms_android/feature/home/adapter/MealPagerAdapter.kt
> +        init {
삭제 완료

2022-12-15 05:52 UTC, limsaehyun approved these changes
수고하셨어요

2022-12-15 05:55 UTC, merged