🔀 :: (#192) Implement application main screen
team-aliens/DMS-Android pull request #193
Opened 2023-02-12 11:56 UTC by Tmdhoon2

## 개요
> 신청 메인 화면을 구현하고 관련 로직을 작성했습니다.

## 작업사항
- 신청 메인 화면 구현
- Navigation 자습실 신청 화면 -> 신청 메인 화면으로 교체
- 신청 메인 화면에서 자습실 화면으로 navigate 로직 구현
- StudyRoomListScreen 에서 TopBar , back stack 기능 구현

## 추가 로 할 말
- 작업을 하며 디자인과 일치하지 않는 몇몇 부분을 발견했습니다.
- 이슈 생성하여 수정할 계획입니다.

2023-02-12 12:40 UTC, JunJaBoy requested changes

2023-02-12 12:40 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/apply/ApplicationMainScreen.kt
> +    val mContext = LocalContext.current
여기 필드 이름 앞에 m을 명시하신 이유가 있나요? m은 클래스의 멤버변수를 의미한다고 알고 있는데, `context`로 해도 상위 스코프의 변수명과 충돌도 없을 뿐더러 의미상으로 더 알맞을 것 같아요.

2023-02-12 12:40 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/apply/ApplicationMainScreen.kt
> +fun ApplicationMainScreen(
패키지 이름도 `application`으로 바꾸어 주셨으면 하고, 개인적으로 ApplicationMainScreen은 MainScreen이랑 혼동이 될 수 있을 것 같아요. Appliation의 뜻이 신청이라는 뜻도 있지만, 애플리케이션 자체를 나타낼 수도 있기 때문에..?

2023-02-12 12:40 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/apply/ApplicationMainScreen.kt
> +fun ApplicationMainScreen(
ApplicationScreen 어떤가요?

2023-02-12 12:40 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/navigator/DmsApp.kt
> +            composable(BottomNavigationItem.Survey.route) { ApplicationMainScreen(navController = navController) }
이 루트 이름도 이제는 Survey보다는 Application이 적절할 것 같아요.

2023-02-13 08:03 UTC, JunJaBoy requested changes

2023-02-13 08:03 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/navigator/BottomNavigationItem.kt
>          BottomNavigationItem(NavigationRoute.BottomNavigation.Survey, R.drawable.ic_plus, "Survey")
여기 루트가 변경되지 않았어욥

2023-02-13 08:23 UTC, JunJaBoy approved these changes

2023-02-13 09:18 UTC, limsaehyun commented on presentation/src/main/java/team/aliens/dms_android/feature/application/ApplicationScreen.kt
> +fun Preview() {
어떤 Preview인지 알 수 있게 명명 부탁드려요

2023-02-13 09:18 UTC, limsaehyun commented on presentation/src/main/java/team/aliens/dms_android/feature/application/ApplicationScreen.kt
> +        Body1(text = context.getString(R.string.Application))
컴포즈 내부적에서 string resources를 가져올 수 있는 `stringResources`를 지원합니다.
해당 기능을 사용해주세요.

2023-02-13 09:18 UTC, limsaehyun commented on presentation/src/main/java/team/aliens/dms_android/feature/application/ApplicationScreen.kt
> +            content = context.getString(R.string.StudyRoomApplyDescription),
여기 동일하게 부탁드려요

2023-02-13 09:18 UTC, limsaehyun commented on presentation/src/main/java/team/aliens/dms_android/feature/application/ApplicationScreen.kt
> +                ) {
DesignSystem Typohraphy 활용 부탁드려요

2023-02-13 11:17 UTC, JunJaBoy approved these changes

2023-02-13 11:17 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/application/ApplicationScreen.kt
> +    buttonOnClick: () -> Unit,
onButtonClick이 좋을 것 같습니당

2023-02-16 15:12 UTC, JunJaBoy approved these changes

2023-02-16 15:16 UTC, merged