🔀 :: (#196) string resource name refactoring
team-aliens/DMS-Android pull request #198
Opened 2023-02-13 16:45 UTC by Tmdhoon2

## 개요
> string resource 들의 이름을 파스칼 케이스에 맞게 수정하였습니다.

## 작업사항
- string resource 폴더 안 resource 이름 수정
- 이름을 수정한 string resource 를 사용하는 파일에서의 string resource 이름 수정

## 추가 로 할 말
- 곳곳에 string resource 로 관리되지 않는 string 들이 있어 추후에 다시 검토가 필요합니다.
- 잔류 신청 화면 퍼블리싱 이후 검토할 계획입니다.

2023-02-14 02:20 UTC, JunJaBoy commented
앞으로 PR하실 때 이슈랑 연결하시면 좋을 것 같아욥

2023-02-14 02:22 UTC, JunJaBoy commented
아 그리고 제가 잘못 이해했나요..? 전에 파스칼 케이스를 스네이크 케이스로 바꾸는 작업 하신다는 걸로 이해 했는데..

2023-02-14 02:24 UTC, Tmdhoon2 commented
> 아 그리고 제가 잘못 이해했나요..? 전에 파스칼 케이스를 스네이크 케이스로 바꾸는 작업 하신다는 걸로 이해 했는데..

아 이 부분은 스네이크 케이스 -> 파스칼 케이스 가 맞습니다!

2023-02-14 04:57 UTC, Leesin0222 reviewed
혹시 기능별로 주석으로 나눠주실 수 있으신가요 ? 이런식으로요

``` kotlin
//자습실 신청
<string name=""application>신청</string>
......

//공지 
<string .....
..
..
```

2023-02-14 05:49 UTC, Tmdhoon2 commented
> 혹시 string들을 각 기능별로 구역을 나눠주시고 주석 달아주실 수 있으신가요 ? 이런식으로요
> 
> ```kotlin
> //자습실 신청
> <string name=""application>신청</string>
> ...
> ...
> 
> //공지 
> <string .....
> ..
> ..
> ```

넵 가능합니다
혹시 이 부분은 어떤 기능에서 사용되는지 알 수 있을까요..??
<img width="30%" alt="스크린샷 2023-02-14 오후 2 49 06" src="https://user-images.githubusercontent.com/102812085/218650732-558e6399-e7cb-496b-a418-c32fe547d82f.png">

2023-02-14 08:58 UTC, JunJaBoy commented
> > 혹시 string들을 각 기능별로 구역을 나눠주시고 주석 달아주실 수 있으신가요 ? 이런식으로요
> > ```kotlin
> > //자습실 신청
> > <string name=""application>신청</string>
> > ...
> > ...
> > 
> > //공지 
> > <string .....
> > ..
> > ..
> > ```
> 
> 넵 가능합니다 혹시 이 부분은 어떤 기능에서 사용되는지 알 수 있을까요..?? <img alt="스크린샷 2023-02-14 오후 2 49 06" width="30%" src="https://user-images.githubusercontent.com/102812085/218650732-558e6399-e7cb-496b-a418-c32fe547d82f.png">

아마 Morning Lunch Dinner 이런 의미로 해석할 수 있을 것 같기는 한데, 코드상으로 따로 Usage가 없네요.. @Leesin0222 @limsaehyun @aahspringaa4

2023-02-14 10:34 UTC, Tmdhoon2 commented
> > > 혹시 string들을 각 기능별로 구역을 나눠주시고 주석 달아주실 수 있으신가요 ? 이런식으로요
> > > ```kotlin
> > > //자습실 신청
> > > <string name=""application>신청</string>
> > > ...
> > > ...
> > > 
> > > //공지 
> > > <string .....
> > > ..
> > > ..
> > > ```
> > 
> > 
> > 넵 가능합니다 혹시 이 부분은 어떤 기능에서 사용되는지 알 수 있을까요..?? <img alt="스크린샷 2023-02-14 오후 2 49 06" width="30%" src="https://user-images.githubusercontent.com/102812085/218650732-558e6399-e7cb-496b-a418-c32fe547d82f.png">
> 
> 아마 Morning Lunch Dinner 이런 의미로 해석할 수 있을 것 같기는 한데, 코드상으로 따로 Usage가 없네요.. @Leesin0222 @limsaehyun @aahspringaa4

우선 사용하지 않는 string resource 는 제거하고, 중복된 resource 도 정리하긴 했습니다..

2023-02-16 15:48 UTC, JunJaBoy requested changes
Comment 확인해 주세요!

2023-02-16 15:48 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/cafeteria/CafeteriaMenu.kt
>                  }
아마 이 부분에서 급식을 서버에서 받아오는 로직이 있어야 해요.. 기본적으로 TextView를 하나 선언해 두시고, 텍스트는 `mutableStateOf("")` state를 참조하는 Text를 하나 만들어 두면 아마 의도한 대로 작동하기는 할 건데.. 나중에 제가 서버 연동 작업 하며 한꺼번에 작업해 볼게요!

2023-02-16 15:48 UTC, JunJaBoy commented on presentation/src/main/res/values/strings.xml
> +    <string name="AnnounceMent">공지</string>
Announcement는 한 단어로 알고 있습니다..

2023-02-17 02:02 UTC, JunJaBoy commented
<img width="1088" alt="image" src="https://user-images.githubusercontent.com/101160207/219530580-8524bec0-5530-40d7-bb0d-5b1351fb99a0.png">
여기 잘못된 참조로 오류가 나는데 확인해 주세요!

2023-02-17 02:20 UTC, JunJaBoy approved these changes

2023-02-17 02:21 UTC, merged