🔀 :: (#197) implement stay application screen
team-aliens/DMS-Android pull request #199
Opened 2023-02-14 11:42 UTC by Tmdhoon2

## 개요
> 잔류 신청 화면 및 관련 로직을 구현했습니다.

## 작업사항
- 잔류 신청 화면 구현
- 여러 곳에서 사용하는 공지사항 알림 추상화
<img width="30%" alt="스크린샷 2023-02-14 오후 12 24 49" src="https://user-images.githubusercontent.com/102812085/218631389-4621bd10-b687-4108-89c2-f413e9701d5b.png">

## 추가 로 할 말
- 아직 잔류 신청 관련 api 가 나오지 않은 관계로 추후에 기능 수정이 필요할 수 있습니다.
- 기능 테스트를 위한 더미 데이터가 있습니다. 추후 서버 연동 과정에서 삭제해야 합니다.
- 현재 string resource 리팩토링 작업 진행중으로 conflict 방지를 위해 string resource 로 관리해야할 것들에 TODO 를 남겨두었습니다.
- 상단 스낵바 구현 로직이 없다면 만들어야할 것 같습니다.
- 신청 메인 화면에서 사용하는 컴포넌트 추상화가 필요합니다.
<img width="30%" alt="스크린샷 2023-02-14 오후 12 28 47" src="https://user-images.githubusercontent.com/102812085/218631911-31559ba8-fda3-401e-87c2-000d601a28d5.png">
<img width="30%" alt="스크린샷 2023-02-14 오후 12 28 33" src="https://user-images.githubusercontent.com/102812085/218631924-7539606a-a666-4cef-a8e4-af8e54f067ea.png">

2023-02-14 11:53 UTC, aahspringaa4 commented on presentation/src/main/java/team/aliens/dms_android/feature/StayApplicationScreen.kt
> +val list = listOf(
mutableList 사용 권장 

공지나 상벌점에 예제있음

2023-02-14 11:53 UTC, aahspringaa4 commented on presentation/src/main/java/team/aliens/dms_android/feature/StayApplicationScreen.kt
> +data class DummyData(
일단은 더미데이터지만 연동시 바로 사용가능하게 네이밍 해주세요.

2023-02-14 11:53 UTC, aahspringaa4 commented on presentation/src/main/java/team/aliens/dms_android/feature/StayApplicationScreen.kt
> +
불필요한 띄어쓰기는 자제

2023-02-14 11:53 UTC, aahspringaa4 commented on presentation/src/main/java/team/aliens/dms_android/feature/StayApplicationScreen.kt
> +                            else DormColor.Gray100
실행문이 한줄이긴한데 그냥 중괄호 열죠

위에는 걍 넘어갔는데 위에 if 문도 중괄호 써주세요(다른곳도)

2023-02-14 11:53 UTC, aahspringaa4 commented on presentation/src/main/java/team/aliens/dms_android/feature/StayApplicationScreen.kt
> +            modifier = Modifier.padding(start = 24.dp)
Trailing Comma

2023-02-14 11:53 UTC, aahspringaa4 commented on presentation/src/main/java/team/aliens/dms_android/feature/cafeteria/CafeteriaScreen.kt
> +
Todo Please

2023-02-15 00:39 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/StayApplicationScreen.kt
> +val list = mutableListOf(
변수명 다시 지어 주시면 좋을 것 같고, 굳이 list의 스코프를 이곳에 두는게 좋을까 싶네요.. 게다가 public으로 선언하는 경우에는 다른 파일에서 참조를 막을 수 없어서 차라리 StayApplicationScreen 내부에 MutableState로 두시고, 그 스코프 내에서 업데이트 하는게 좋지 않을까 싶습니당

2023-02-15 00:43 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/StayApplicationScreen.kt
> +val list = mutableListOf(
사실 이것 뿐만 아니라, 우리 코드 전체적으로 접근 제한자나 스코프 지정이 조금 애매하다..? 라는 생각이 들어요.. 예를 들어서 data 모듈의 HttpHandler나, presentation 계층의 대부분의 클래스들이 public으로 선언되어 있어서, 혹시 모를 참조로 인해 코드가 꼬일 수도 있을 것 같아요. 언제 한 번 고민해서 수정해야 할 것 같기는 합니다.

2023-02-15 01:47 UTC, JunJaBoy approved these changes

2023-02-15 01:47 UTC, JunJaBoy commented on design-system/src/main/java/team/aliens/design_system/floatingnotice/FloatingNotice.kt
> +                contentDescription = "NoticeIcon",
다른 컴포넌트에는 description을 대부분 null로 해두었던 것 같은데.. 크게 상관은 없을 것 같네요

2023-02-17 02:51 UTC, JunJaBoy requested changes

2023-02-17 02:51 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/StayApplicationScreen.kt
> +    )
recomposition마다 새로운 클래스 정의를 만들어 주어야 해서 비효율적일 것 같아욥..  함수 밖으로 빼는게 좋겠어요 !

2023-02-17 02:51 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/StayApplicationScreen.kt
> +        )
서버에서 값을 받아오고 나서는 값이 변할 일이 없는 것 같은데, 아마 immutable 객체로 선언해도 될 것 같네요

2023-02-17 02:51 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/StayApplicationScreen.kt
> +        )
이 부분은 제가 서버 연동하면서 바꿔 볼게요!

2023-02-17 02:51 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/StayApplicationScreen.kt
> +                            val isSelectedItem = (selectedItem == stayApplicationTitle)
isItemExpanded, isItemSelected라고 명명하는게 문법에 더 괜찮을 것 같아요

2023-02-17 02:51 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/StayApplicationScreen.kt
> +        var isButtonVisible by remember { mutableStateOf(false) }
이 변수들 뜻이 와닿지 않는데.. 혹시 item이 어떤걸 가리키나요??

2023-02-17 02:51 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/StayApplicationScreen.kt
> +    onDrawableClick: () -> Unit,
제가 이해한 바로는 이 코드가 아이템을 펼칠 때 로직인 것 같은데, onUnfold가 괜찮을 것 같네요

2023-02-17 02:51 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/StayApplicationScreen.kt
> +                    },
혹시 디자인적으로 차이가 있어서 이렇게 해 두신건가요?

2023-02-17 03:44 UTC, limsaehyun commented on presentation/src/main/java/team/aliens/dms_android/feature/StayApplicationScreen.kt
> +val list = mutableListOf(
전반적인 아키텍처링에 관련해서 @aahspringaa4 에게 이렇게 설계한 이유와 아키텍처 의도를 듣고 가는게 좋을 것 같네요.

2023-02-17 03:48 UTC, limsaehyun commented on presentation/src/main/java/team/aliens/dms_android/feature/StayApplicationScreen.kt
> +val list = mutableListOf(
언급해주신 부분 관련해서 UDF를 유지하기 위해 MVI패턴에 관련한 이야기가 나왔어요
그래서 현명님이 상태 관리를 위한 BaseViewModel를 만들어 두셨는데,
관련해서 설명 들어보시면 좋을 것 같네요.

2023-02-17 04:13 UTC, Tmdhoon2 commented on presentation/src/main/java/team/aliens/dms_android/feature/StayApplicationScreen.kt
> +        var isButtonVisible by remember { mutableStateOf(false) }
<img width="215" alt="스크린샷 2023-02-17 오후 1 12 07" src="https://user-images.githubusercontent.com/102812085/219547631-f257ef75-f807-4c30-998a-04f527194543.png">

여기 하나하나를 Item 이라고 생각해서 변수명을 짓긴 했는데 바꿀 필요성이 있어보이네요

2023-02-17 08:14 UTC, JunJaBoy approved these changes

2023-02-17 08:17 UTC, merged