🔀 :: (#201) implement remain entities and repositories in domain and data layer
team-aliens/DMS-Android pull request #202
Opened 2023-02-17 13:34 UTC by JunJaBoy

## 개요
> 서버 통신을 위한 추상적인 도메인 엔티티, 리포지토리를 추가하고, 데이터 레이어에서 구현합니다.

## 작업사항
### domain layer
- 잔류에 관한 엔티티 구현
- 잔류에 관한 리포지토리 구현
- 잔류에 관한 유즈케이스 구현

### data layer
- 잔류에 관한 리포지토리 구현체 구현
- 잔류에 관한 API 인터페이스, URL 구현 및 의존성 주입 설정
- 잔류에 관한 DataSource 인터페이스, 구현체 구현 및 의존성 주입 설정

### di layer
- NetworkModule에 RemainApi 제공 로직 구현
- RepositoryModule에 RemainRepository 바인딩 로직 구현

## 추가 로 할 말

2023-02-17 15:48 UTC, Tmdhoon2 requested changes

2023-02-17 15:48 UTC, Tmdhoon2 commented on data/src/main/java/team/aliens/data/remote/response/remain/FetchAvailableRemainTimeResponse.kt
> +    )
this 를 따로 명시해주신 이유가 있나요??

2023-02-17 15:48 UTC, Tmdhoon2 commented on di/src/main/java/team/aliens/di/NetWorkModule.kt
> +    @Singleton
이번에 이 부분이 헷갈려서 좀 찾아봤는데 InstallIn 으로 SingletonComponent 를 명시해줘도 실제로 객체를 Singleton 으로 생성하려면 어노테이션을 따로 붙어줘야 하네요..!! 혹시 제가 잘 이해했다면 위에서 사용되는 함수들에도 Singleton 어노테이션을 붙여야 하는게 맞나요??

2023-02-17 15:48 UTC, Tmdhoon2 commented on di/src/main/java/team/aliens/di/RepositoryModule.kt
> +    @Singleton
여기도 마찬가지입니다!

2023-02-17 23:20 UTC, JunJaBoy commented on di/src/main/java/team/aliens/di/NetWorkModule.kt
> +    @Singleton
넵 맞아용.. 이 부분은 따로 이슈로 빼려고 했는데 깜빡했네요;;

2023-02-17 23:21 UTC, JunJaBoy commented on data/src/main/java/team/aliens/data/remote/response/remain/FetchAvailableRemainTimeResponse.kt
> +    )
굳이 없기는 한데 확장함수이다보니 새로운 인스턴스를 생성할때 클래스의 멤버변수를 사용한다?는 느낌으로 써 봤어욥

2023-02-18 03:37 UTC, Tmdhoon2 approved these changes

2023-02-18 12:59 UTC, merged