🔀 :: (#210) implement floating notice click event
team-aliens/DMS-Android pull request #211
Opened 2023-02-22 11:15 UTC by Tmdhoon2

## 개요
> 급식 화면의 공지 알림 컴포넌트 아이콘을 클릭했을때 공지 화면으로 전환되는 로직을 구현했습니다.

## 작업사항
- CafeterialScreen 파라미터로 moveToNoticeScreen 함수 추가
- bottomSelectedItem 값 BottomNavBar 함수에서 DmsApp 함수로 이동
- 공지 화면으로 이동 시 공지 바텀 아이템 선택 효과 구현

## 추가 로 할 말
- 추후에 공지 알림을 상황에 따라 표시해주는 로직 구현이 필요할것 같습니다.
- ex 공지가 없는 경우 공지 알림 표시 X
- ex 유저가 공지 알림을 통해 새 공지를 확인한 경우 공지 알림 표시 X

2023-02-22 12:10 UTC, JunJaBoy requested changes

2023-02-22 12:10 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/cafeteria/CafeteriaScreen.kt
> +    moveToNoticeScreen: () -> Unit,
이 파라미터를 사용 하는 방법도 괜찮은데, 특정 동작만을 하는 함수가 많은 함수를 거치지 않는가 싶네요.. 개인적으로 상위  composable에서 새로운 NavHostController 인스턴스를 생성해서 CafeteriaScreen을 통해 이 함수로 전달받았으면 합니다.

2023-02-22 12:10 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/cafeteria/CafeteriaScreen.kt
> +    moveToNoticeScreen: () -> Unit,
공지 버튼을 누르면 공지 페이지로 navigate하는 느낌인가요?

2023-02-22 12:11 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/cafeteria/CafeteriaScreen.kt
> +    moveToNoticeScreen: () -> Unit,
혹시 카페테리아에서 공지를 누르면 공지 페이지가 먼저 뜨고, 뒤로 가기 버튼을 누르면 공지 리스트 페이지가 뜨나요?

2023-02-22 12:22 UTC, Tmdhoon2 commented on presentation/src/main/java/team/aliens/dms_android/feature/cafeteria/CafeteriaScreen.kt
> +    moveToNoticeScreen: () -> Unit,
공지 알림에서 버튼을 누르면 단순히 공지 리스트 페이지로 전환되는 로직입니다.
이동 후 뒤로가기 버튼을 누르면 카페테리아로 돌아갑니다.
버튼 클릭 -> 공지 리스트 페이지

2023-02-22 12:25 UTC, Tmdhoon2 commented on presentation/src/main/java/team/aliens/dms_android/feature/cafeteria/CafeteriaScreen.kt
> +    moveToNoticeScreen: () -> Unit,
수정했습니다!

2023-02-22 23:13 UTC, JunJaBoy requested changes

2023-02-22 23:13 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/cafeteria/CafeteriaScreen.kt
> +    moveToNoticeScreen: () -> Unit,
음.. 그렇다면 navController에 navigate를 위임하는 편이 괜찮을 것 같다는게 저의 생각.. 함수 객체가 여러 composable의 함수를 거쳐 전달되는게 아무래도 무거운 느낌이 들기도 하고, composable 트리 상위 계층에 있는 composable이 하위 Composable에게 이런 부분까지 결정해 주기에는 상위 composable의 코드가 팽창할 것 같아요. DMS의 다른 코드도 대부분 navController를 받아서, 스스로 목적지로 이동하는 방식이던데, 한 번 제 말 생각해 보시고 결정해 주세용

2023-02-23 00:13 UTC, Tmdhoon2 commented on presentation/src/main/java/team/aliens/dms_android/feature/cafeteria/CafeteriaScreen.kt
> +    moveToNoticeScreen: () -> Unit,
수정했습니다!

2023-02-23 11:41 UTC, JunJaBoy approved these changes

2023-02-23 11:45 UTC, merged