🔀 :: (#212) bottom navigation bar refactoring
team-aliens/DMS-Android pull request #218
Opened 2023-02-23 13:08 UTC by Tmdhoon2

## 개요
> 바텀 내비게이션 바를 리팩토링 했습니다.

## 작업사항
- 기존에 없던 아이템별 텍스트를 추가했습니다.
- 선택/비선택 구분이 명확하게 컬러를 수정했습니다.
<img width="381" alt="스크린샷 2023-02-23 오후 10 07 03" src="https://user-images.githubusercontent.com/102812085/220915108-2f29bb9d-8137-4635-bdff-0c3bfaf8a73f.png">

## 추가 로 할 말
- 추가로 코너 라운드 구현이 필요합니다.

2023-02-23 13:27 UTC, JunJaBoy requested changes

2023-02-23 13:27 UTC, JunJaBoy commented on design-system/src/main/java/team/aliens/design_system/typography/typography.kt
> +    val bottomNavItem = TextStyle(
bottomNavigation 아이템별 텍스트를 의미한다면 bottomNavItemLabel이 괜찮을 것 같아욥

2023-02-23 13:27 UTC, JunJaBoy commented on design-system/src/main/java/team/aliens/design_system/typography/typography.kt
> +fun BottomNavItemText(
여기도 bottomNavigationItemLabel 이라고 바꿔주세용

2023-02-23 13:27 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/navigator/DmsApp.kt
> +    val unselectedColor = DormColor.Gray500
이거 state로 감싸거나, 파일 스코프로 빼주세요!

2023-02-23 13:27 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/navigator/DmsApp.kt
> +    }
변수 이름을 selectedItem과 같이 이해하기 편하게 바꾸어 주시면 좋을 것 같고, 숫자로 나타내는 것보다 그냥 route 스트링 자체를 state로 나타낸 뒤, 밑에서 참조할 때는 selected~ == navController.currentDestination으로 해 보실 수 있나요?

2023-02-23 14:35 UTC, Tmdhoon2 commented on presentation/src/main/java/team/aliens/dms_android/feature/navigator/DmsApp.kt
> +    }
어.. 그 혹시 다시 설명해주실 수 있나요....

2023-02-24 03:51 UTC, JunJaBoy approved these changes

2023-02-24 04:01 UTC, merged