🔀 :: Login Business Logic
team-aliens/DMS-Android pull request #26
Opened 2022-10-07 05:11 UTC by aahspringaa4

2022-10-07 05:21 UTC, limsaehyun requested changes

2022-10-07 05:21 UTC, limsaehyun commented on auth_data/src/main/java/com/example/auth_data/remote/datasource/declaration/RemoteUserDataSource.kt
> +        signInRequest: SignInRequest
trailingComma 지켜주세요

2022-10-07 05:21 UTC, limsaehyun commented on auth_data/src/main/java/com/example/auth_data/remote/api/UserApi.kt
> +    @POST (DmsUrl.login)
Url 모두를 하나의 Object에 담기보다,
기능의 종류별로 object를 만드는 편이 더 맞지 않나요?

2022-10-07 05:21 UTC, limsaehyun commented on auth_data/src/main/java/com/example/auth_data/repository/UserRepositoryImpl.kt
> +    private val localUserDataSource: LocalUserDataSource
trailingComma 지켜주세요

2022-10-07 05:21 UTC, limsaehyun commented on auth_data/src/main/java/com/example/auth_data/repository/UserRepositoryImpl.kt
> +        recentRoomBoolean = recentBoolean
trailingComma 지켜주세요

2022-10-07 05:21 UTC, limsaehyun commented on local_database/src/main/java/com/example/local_database/storage/implementation/UserDataStorageImpl.kt
> +        getSharedPreference().getBoolean(SURVEY.toString(), false)
sharedPreference의 key를 저장하는 부분 아닌가요?
SURVEY는 Boolean형인데 이러면
`getSharedPreference().getBoolean("false", false) `와 같은 코드가 되어버립니다.

2022-10-07 05:21 UTC, limsaehyun commented on local_database/src/main/java/com/example/local_database/datasource/implementation/LocalUserDataSourceImpl.kt
> +            return UserVisibleParam(
이러한 형태의 코드는 .toParam() 이러한 형식으로 확장 함수로 관리하면 더 편할 것 같아요.

2022-10-07 05:21 UTC, limsaehyun commented on local_database/src/main/java/com/example/local_database/datasource/implementation/LocalUserDataSourceImpl.kt
> +        TODO("Not yet implemented")
이 부분은 왜 구현이 안돼어있나요?

2022-10-11 08:15 UTC, kimdaehee0824 commented
ios 들들은 왜 넣은거에요?

2022-10-11 14:12 UTC, limsaehyun approved these changes
👍🏿

2022-10-11 14:12 UTC, limsaehyun commented on local_database/src/main/java/com/example/local_database/storage/implementation/UserDataStorageImpl.kt
> +    @ApplicationContext private val context: Context
trailingComma

2022-10-11 14:12 UTC, limsaehyun commented on local_database/src/main/java/com/example/local_database/repository/LocalUserRepositoryImpl.kt
> +    private val localUserDataSource: LocalUserDataSource
trailingComma

2022-10-11 14:12 UTC, limsaehyun commented on auth_domain/src/main/java/com/example/auth_domain/usecase/RemoteSignInUseCase.kt
> +    private val userRepository: UserRepository
trailingComma

2022-10-11 14:12 UTC, limsaehyun commented on auth_data/src/main/java/com/example/auth_data/util/HttpHandler.kt
> +class HttpHandler<T> {
이 HttpHandler가 dekekt 기준으로는 여러가지의 규칙을 어기는 것을 확인했어요.
추후에 개선하면 좋을 것 같네요.

2022-10-11 14:12 UTC, limsaehyun commented on auth_data/src/main/java/com/example/auth_data/remote/datasource/implementation/RemoteUserDataSourceImpl.kt
> +    private val userApi: UserApi
trailingComma

2022-10-11 14:12 UTC, limsaehyun commented on auth_data/src/main/java/com/example/auth_data/remote/datasource/implementation/RemoteUserDataSourceImpl.kt
> +        signInRequest: SignInRequest
trailingComma

2022-10-11 14:16 UTC, merged