🔀 :: 333 refactor fetch studyroom list logic
team-aliens/DMS-Android pull request #343
Opened 2023-03-24 15:19 UTC by Tmdhoon2

## 개요
> 자습실 이용시간에 따른 목록 조회 / 신청 / 취소 / 상세보기 로직을 리팩토링 했습니다

## 작업사항
- 조회 / 신청 / 취소 / 상세보기 로직에 uuid 파라미터 추가
- 이용 시간 목록 조회 로직 및 뷰 리팩토링
- 프로필 이미지 변경 로직 중복 요청 방지를 위한 버튼 비활성화 로직 구현

## 추가 로 할 말
- UUID 에 null 처리는 이용 시간이 설정되어 있지 않은 학교의 경우 이용 시간 값을 null 로 보내야 하기 때문입니다.
- 자습실 상세보기에서 자리 컬러가 검정색인 경우 글자가 보이지 않습니다 (배경 색과 동일해서 그런걸로 추정)

2023-03-25 02:23 UTC, JunJaBoy requested changes

2023-03-25 02:23 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/image/ConfirmImageScreen.kt
> +                    confirmImageViewModel.setConfirmButtonState(true)
이 친구는 아마 뷰모델에 로직이 있어야 할 것 같은데.. 로그인 스크린에 이렇게 되어있었다면 죄송합니다

2023-03-25 02:23 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/navigator/NavigationRoute.kt
> +    const val StudyRoomDetail = "studyRoomDetail/{seatId}/{timeSlot}"
엥 그러고보니 path variable들이 모두 카멜케이스네요

2023-03-25 02:23 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/navigator/NavigationRoute.kt
> +    const val StudyRoomDetail = "studyRoomDetail/{seatId}/{timeSlot}"
상관 없을 것 같긴 한데 리팩토링중인 데이터에는 명세서와 동일하게 케밥케이스로 작성중입니다

2023-03-25 02:23 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/navigator/RootDms.kt
> +                    navArgument("timeSlot") { type = NavType.StringType },
나중에 아규먼트들 상수값으로 관리하면 좋겠어요

2023-03-25 02:23 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/navigator/RootDms.kt
> +                        timeSlot = UUID.fromString(timeSlot),
음 혹시 UUID.fromString은 not-null을 아규먼트로 받나요? 그렇다면 여제껏 UUID를 옵셔널로 받는 로직은 필요 없어질 것 같은데.. 한 번 확인해 주세요

2023-03-25 02:23 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/studyroom/StudyRoomDetailScreen.kt
> +    timeSlot: UUID?,
만약 timeSlot이 널일 경우에는 어떤 화면이 표시될까요? 그리고 roomId랑 timeSlot 모두 호출자와 같은 뷰모델을 써서 뷰모델 안에서 관리하거나, navArgument로 관리하는 방법을 함께 얘기해보고 싶어요

2023-03-25 02:23 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/studyroom/StudyRoomDetailScreen.kt
> +            type = SeatType.toSeatType(seat.status)
제 인텔리센스가 이상한 건지 모르겠는데 이상하게 이런곳에는 후행컴마 안 찍어주더라고요.. 승훈님도 한 번씩 확인해 보시면 좋을듯

2023-03-25 02:23 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/studyroom/StudyRoomListScreen.kt
> +    var selectedIndex by remember { mutableStateOf(0) }
앞뒤 문맥 없이 sectedIndex를 보면 어떤 의미의 Index가 떠오르시나요? 다른 사람이 이해하기 좋은 네이밍은 아닌 것 같아여..

2023-03-25 02:23 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/studyroom/StudyRoomListScreen.kt
> +    var selectedAvailableTime by remember { mutableStateOf("") }
이런 네이밍은 아주 좋아요

2023-03-25 02:23 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/studyroom/StudyRoomListScreen.kt
> +                    content = "자습실 신청 가능 시간 : ${studyRoomState.startAt} ~ ${studyRoomState.endAt}",
한글 부분만 스트링 리소스로 빼주세요

2023-03-25 02:23 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/studyroom/StudyRoomListScreen.kt
> +                    content = "자습실 신청 가능 시간 : ${studyRoomState.startAt} ~ ${studyRoomState.endAt}",
이 스트링 리소스는 새로운 리소스 규칙으로 작성해 주세요

2023-03-25 02:23 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/studyroom/StudyRoomListScreen.kt
> +                    // slider icon
슬라이더 아이콘이 뭔가요?
![](https://lh3.googleusercontent.com/kT0mNYkbw5j6ZtQx2bgwQipVHheZf7K7ut6lGXRugITIdOawOZhzN2N-ku99zBu6pMEFENskgJQD_ITupeNxWJRhQzXQ3Xe9W-uE3Ovl-Hbybi0OPg=w1064-v0)
이런건가요?

2023-03-25 02:23 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/studyroom/StudyRoomListScreen.kt
> +                        color = DormColor.DormPrimary,
DormTheme.colors.primary 써주세요

2023-03-25 02:23 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/studyroom/StudyRoomListScreen.kt
> +                        color = DormColor.DormPrimary,
혹시 제가 놓친 부분 있을수도 있는데 다 DormTheme로 바꿔주세요

2023-03-25 02:23 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/studyroom/StudyRoomListScreen.kt
> +private fun setAvailableTime(
어떤 뷰에 대한 속성을 바꾸는게 아닌데, setAvailableTime이라는 네이밍이 적합하지 못한 것 같아요

2023-03-25 02:23 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/studyroom/StudyRoomListScreen.kt
> +private fun setAvailableTime(
이 함수를 꼭 사용하시는 이유가 있나요?

2023-03-25 02:23 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/studyroom/StudyRoomListUiState.kt
> +    var timeSlot: UUID? = null,
timeSlot을 널로 주신 이유가 있을까요

2023-03-25 02:23 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/studyroom/StudyRoomListUiState.kt
> +    var timeSlot: UUID? = null,
UUID.fromString("") 이런 것처럼 기본값을 주면 안되나요(예시로 말씀드린겁니다.. 실제로 "" 주면 이상한 값이 생성될거에요)

2023-03-25 02:23 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/studyroom/StudyRoomListViewModel.kt
>          ) : UiEvent() // todo implement
오류 없이 작동할까요? UIEvent 부분은 나중에 아주 깊게 다시 생각해 보죠

2023-03-25 02:23 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/studyroom/StudyRoomListViewModel.kt
> +                if (exception != NotFoundException()) {
엥 완전 이해 안되네요

2023-03-25 02:23 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/studyroom/StudyRoomListViewModel.kt
> +                if (exception != NotFoundException()) {
exception이 notfoudexception이면 어떻게 되나요

2023-03-25 02:23 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/studyroom/StudyRoomListViewModel.kt
> +                if (exception != NotFoundException()) {
exception이 notfoundexception일 때만 `if (exception is NotFoundException)`을 사용해서 분기하면 안되나요?

2023-03-25 02:23 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/studyroom/StudyRoomListViewModel.kt
> +                studyRoomListUseCase.execute(_uiState.value.timeSlot)
선택된 timeslot 변수 선언해서 변수를 execute에 넘겨주는게 이해가 잘 될 것 같네요

2023-03-25 02:23 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/studyroom/StudyRoomListViewModel.kt
>  }
위에서부터 계속 궁금했던게, 여기에선 not-null UUID를 받는데, 추상화가 높은 계층으로 갈수록 nullable 값으로 바뀌네요..

2023-03-25 02:23 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/viewmodel/image/ConfirmImageViewModel.kt
> +
MutableState를 사용할건지, Event를 사용할건지 상의해봐야겠어요

2023-03-25 02:23 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/viewmodel/image/ConfirmImageViewModel.kt
> +        }
제 코드에도 아마 이런게 있을텐데, 나중에는 Dispatchers.Main을 빼는 방향으로 얘기해 봅시다

2023-03-25 02:23 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/viewmodel/studyroom/StudyRoomDetailUiState.kt
> +    var timeSlot: UUID? = null,
2222222

2023-03-25 02:23 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/viewmodel/studyroom/StudyRoomDetailsViewModel.kt
> +            val timeSlot: UUID?,
333333

2023-03-25 02:23 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/viewmodel/studyroom/StudyRoomDetailsViewModel.kt
> +                    data = _uiState.value.timeSlot
data가 의미가 있을까요.. 일단 살려둡시다

2023-03-25 02:23 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/viewmodel/studyroom/StudyRoomDetailsViewModel.kt
> +                    data = _uiState.value.timeSlot
그리고 timeSlot 아규먼트 접근 과정을 보여주기보다 변수 하나 선언해서 그 변수 넘겨주는게 가독성이 좋을 것 같아요

2023-03-25 02:23 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/viewmodel/studyroom/StudyRoomDetailsViewModel.kt
> +                    data = _uiState.value.timeSlot
라는게 개인적인 생각

2023-03-25 02:57 UTC, Tmdhoon2 commented on data/src/main/java/team/aliens/data/repository/StudyRoomRepositoryImpl.kt
> +            timeSlot = applyStudyRoomParam.timeSlot,
applyStudyRoomParam 을 사용하지 않고 seatId, timeSlot 을 각각 파라미터로 받으면 될 것 같다는 말씀이실까요??

2023-03-25 02:58 UTC, Tmdhoon2 commented on data/src/main/java/team/aliens/data/repository/StudyRoomRepositoryImpl.kt
> +            timeSlot = applyStudyRoomParam.timeSlot,
아 맞으시군요 param 을 따로 사용하지 않고 각각 전달

2023-03-25 03:37 UTC, Tmdhoon2 commented on data/src/main/java/team/aliens/data/remote/api/StudyRoomApi.kt
> +        @Query("time_slot") timeSlot: UUID?,
해결했습니다!

2023-03-25 03:37 UTC, Tmdhoon2 commented on presentation/src/main/java/team/aliens/dms_android/viewmodel/image/ConfirmImageViewModel.kt
> +        }
좋습니다!

2023-03-25 05:42 UTC, Tmdhoon2 commented on presentation/src/main/java/team/aliens/dms_android/feature/image/ConfirmImageScreen.kt
> +                    confirmImageViewModel.setConfirmButtonState(true)
헉 로그인 스크린은 스크린에서 뷰모델 함수를 호출하고 있긴 한데.. 개선해보겠습니다!

2023-03-25 05:51 UTC, Tmdhoon2 commented on presentation/src/main/java/team/aliens/dms_android/feature/navigator/NavigationRoute.kt
> +    const val StudyRoomDetail = "studyRoomDetail/{seatId}/{timeSlot}"
음 그러면 준수님이 리팩토링 하시면서 케밥케이스로 바꾸는걸로 해도 괜찮으실까요??

2023-03-25 05:53 UTC, Tmdhoon2 commented on presentation/src/main/java/team/aliens/dms_android/feature/navigator/RootDms.kt
> +                        timeSlot = UUID.fromString(timeSlot),
위에서도 말씀드렸긴 한데, 명세에 null 이 잘못 쓰여 있던거라고 하시네요.. 옵셔널 제거 했습니다!

2023-03-25 06:42 UTC, Tmdhoon2 commented on presentation/src/main/java/team/aliens/dms_android/feature/studyroom/StudyRoomListScreen.kt
> +                    content = "자습실 신청 가능 시간 : ${studyRoomState.startAt} ~ ${studyRoomState.endAt}",
해결했습니다!

2023-03-25 06:44 UTC, Tmdhoon2 commented on presentation/src/main/java/team/aliens/dms_android/feature/studyroom/StudyRoomListScreen.kt
> +                    // slider icon
일단 제가 쓴게 아니긴 한데.. 
<img width="30" alt="스크린샷 2023-03-25 오후 3 43 09" src="https://user-images.githubusercontent.com/102812085/227701586-52ce217c-fa15-4db1-b220-0965b32360dd.png">
이거 같네요

2023-03-25 07:26 UTC, Tmdhoon2 commented on presentation/src/main/java/team/aliens/dms_android/feature/studyroom/StudyRoomListScreen.kt
> +private fun setAvailableTime(
자습실 이용 시간 안내랑 필터에서 시간을 조합해서 텍스트 형태로 만드는데 사용합니다

2023-03-25 09:15 UTC, Tmdhoon2 commented on presentation/src/main/java/team/aliens/dms_android/feature/studyroom/StudyRoomListUiState.kt
> +    var timeSlot: UUID? = null,
음 처음에 uuid 를 사용할 때는 저런식으로 주려고 했었는데, "" 부분에 마땅한 값이 떠오르지 않았어요.. 혹시 좋은 생각이 있으시면 공유 부탁드려요

2023-03-25 09:17 UTC, Tmdhoon2 commented on presentation/src/main/java/team/aliens/dms_android/feature/studyroom/StudyRoomListViewModel.kt
> +                if (exception != NotFoundException()) {
수정했습니다!

2023-03-25 11:06 UTC, JunJaBoy requested changes

2023-03-25 11:06 UTC, JunJaBoy commented on domain/src/main/java/team/aliens/domain/usecase/studyroom/RemoteApplySeatUseCase.kt
> +    override suspend fun execute(applyStudyRoomParam: ApplyStudyRoomParam) {
음 일단 그냥 진행하기로 하죠

2023-03-25 11:06 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/studyroom/StudyRoomListScreen.kt
> +                    // slider icon
아 제가 썻나봐요

2023-03-25 11:06 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/studyroom/StudyRoomListScreen.kt
> +private fun setAvailableTime(
꼭 함수를 사용하셔야 한다면 네이밍 수정이 필요할 것 같아요

2023-03-25 11:06 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/viewmodel/studyroom/StudyRoomDetailsViewModel.kt
> +        timeSlot: UUID?,
여기 수정 안된 것 같아요

2023-03-25 11:06 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/viewmodel/studyroom/StudyRoomDetailsViewModel.kt
> +            timeSlot = timeSlot!!,
nullable을 not null로 바꿔주는데..

2023-03-25 11:06 UTC, JunJaBoy commented on presentation/src/main/res/values/strings.xml
> +    <string name="study_room_apply_time">자습실 신청 가능 시간 : %s</string>
엥 이 브랜치는 스트링 리소스 리팩토링이 적용되지 않은 건가요

2023-03-25 14:35 UTC, Tmdhoon2 commented on domain/src/main/java/team/aliens/domain/param/ApplyStudyRoomParam.kt
> +)
음.. 그러면 usecase 에는 param 이 아니라 각각의 값을 전달해주어야 하나요..??

2023-03-27 01:24 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/studyroom/StudyRoomListViewModel.kt
> +                    data = timeSlot!!,
요거 not null assertion 하시는 이유가 있나요? 제가 코드를 잘 모르기는 하지만, 그냥 데이터 생성되는 처음부터 not-null로 전달해주면 안되는건가요?

2023-03-27 01:24 UTC, JunJaBoy commented on domain/src/main/java/team/aliens/domain/param/ApplyStudyRoomParam.kt
> +)
네네 이건 리팩토링 하면서 생각해 봅시다

2023-03-27 01:26 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/navigator/NavigationRoute.kt
> +    const val StudyRoomDetail = "studyRoomDetail/{seatId}/{timeSlot}"
네네 승훈님은 이대로 그냥 작셩하셔도 됩니당

2023-03-27 01:28 UTC, JunJaBoy requested changes

2023-03-27 01:28 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/studyroom/StudyRoomListScreen.kt
> +                        color = DormColor.DormPrimary,
이거 안 고쳐졌네요

2023-03-27 01:50 UTC, Tmdhoon2 commented on data/src/main/java/team/aliens/data/remote/datasource/declaration/RemoteStudyRoomDataSource.kt
> +        timeSlot: UUID?,
해결했습니다!

2023-03-28 03:34 UTC, JunJaBoy approved these changes

2023-03-28 03:39 UTC, merged