🔀 :: (#342) data remote local 레이어 구현
team-aliens/DMS-Android pull request #355
Opened 2023-04-04 10:45 UTC by JunJaBoy

## 개요
> data remote local 레이어를 리팩토링합니다

## 작업사항
### data
- Repository Implementation 구현
- facade 구현
- DataSource 원형 구현

### remote
- URL 클래스로 관리
- Http Property 클래스로 관리
- DataSource Implementation 구현
- Request 및 Response 구현
- Retrofit Service 구현

### local
- Room 구현
- DataStore 구현
- Room Property로 관리
- DataStore Property로 관리
- DataSource Implementation 구현

## 추가 로 할 말
😵‍💫

2023-04-04 14:28 UTC, chlgkdms approved these changes

2023-04-05 06:40 UTC, aahspringaa4 requested changes

2023-04-05 06:40 UTC, aahspringaa4 commented on data/src/main/java/team/aliens/data/_datasource/local/LocalSchoolDataSource.kt
> +    suspend fun findRemainsServiceEnabled(): Boolean
find 라는 네이밍이 그렇게 좋진 않은 네이밍인것 같네요

2023-04-05 06:40 UTC, aahspringaa4 commented on data/src/main/java/team/aliens/data/_datasource/local/LocalAuthDataSource.kt
> +        token: Token,
다른곳 다 포함한 리뷰인데 인자값 하나인데 굳이 줄을 바꿔야하나요?

2023-04-05 06:40 UTC, aahspringaa4 commented on data/src/main/java/team/aliens/data/_datasource/remote/RemoteStudentDataSource.kt
> +    ): ExamineStudentNumberOutput
data class 안쓰는 이유는 뭔가요?

2023-04-05 06:40 UTC, aahspringaa4 commented on data/src/main/java/team/aliens/data/_facade/AuthorizationFacade.kt
> +    suspend fun accessToken(): String {
반환형에 대입하는 코틀린 문법으로 사용하면 안되나요?

2023-04-05 06:40 UTC, aahspringaa4 commented on data/src/main/java/team/aliens/data/_facade/AuthorizationFacade.kt
> +    suspend fun accessToken(): String {
다른곳 다 포함하는 리뷰입니다.

2023-04-05 08:17 UTC, limsaehyun commented on data/src/main/java/team/aliens/data/_facade/AuthorizationFacade.kt
> +class AuthorizationFacade @Inject constructor(
Facade Pattern을 사용하신 이유가 있을까요?
localAuthDataSource을 호출하여 리턴하는 단순한 로직인데
굳이 필요할까 싶네요

2023-04-05 08:20 UTC, limsaehyun commented
@JunJaBoy conflict 발생했네요

2023-04-05 09:16 UTC, JunJaBoy commented on data/src/main/java/team/aliens/data/_datasource/local/LocalAuthDataSource.kt
> +        token: Token,
음 이 부분 한 번 컨벤션 회의로 잡고 가야겠네요

2023-04-05 12:51 UTC, Tmdhoon2 commented on remote/src/main/java/team/aliens/remote/http/AuthorizationInterceptor.kt
> +        if (accessTokenAvailable.not()) {
! 로 처리하는게 일관성 있지 않을까요

2023-04-05 12:51 UTC, Tmdhoon2 commented on remote/src/main/java/team/aliens/remote/model/notice/FetchWhetherNewNoticesExistResponse.kt
> +    @SerializedName("whether_new_notices") val newNotices: Boolean,
여기도 변수 이름 바꾸는게 좋을 것 같아요

2023-04-05 12:51 UTC, Tmdhoon2 commented on remote/src/main/java/team/aliens/remote/util/DateParseUtil.kt
> +    return formatter.parse(this)!!
여기는 혹시 옵셔널 처리가 왜 되어 있나요??

2023-04-23 13:42 UTC, closed without merging