🔀 :: (#342) data remote local 레이어 구현 conflict 해결
team-aliens/DMS-Android pull request #363
Opened 2023-04-05 14:12 UTC by JunJaBoy

## 개요
> data remote local 레이어를 리팩토링합니다

## 작업사항
### data
- Repository Implementation 구현
- facade 구현
- DataSource 원형 구현

### remote
- URL 클래스로 관리
- Http Property 클래스로 관리
- DataSource Implementation 구현
- Request 및 Response 구현
- Retrofit Service 구현

### local
- Room 구현
- DataStore 구현
- Room Property로 관리
- DataStore Property로 관리
- DataSource Implementation 구현

## 추가 로 할 말
😵‍💫

2023-04-10 23:37 UTC, limsaehyun commented on buildSrc/src/main/kotlin/ProjectProperties.kt
> +    const val VERSION_NAME = "v1.0.3"
1.0.2 버전을 건너뛴 이유가 뭔가요?

2023-04-10 23:37 UTC, limsaehyun commented on presentation/src/main/java/team/aliens/dms_android/feature/application/ApplicationScreen.kt
> +        if (isStudyRoomServiceEnabled!!) {
위험한 방식입니다. !! 는 지양해주세요

2023-04-11 01:55 UTC, JunJaBoy commented on buildSrc/src/main/kotlin/ProjectProperties.kt
> +    const val VERSION_NAME = "v1.0.3"
이 브랜치 작업하기 전에 2버전 배포를 한 적이 있습니당

2023-04-11 10:41 UTC, Tmdhoon2 requested changes

2023-04-11 10:41 UTC, Tmdhoon2 commented on local/src/main/java/team/aliens/local/room/common/RoomProperty.kt
> +        const val DbName = "dorm-database"
원래 데이터베이스 이름은 케밥 케이스로 짓나요??

2023-04-11 12:09 UTC, JunJaBoy commented on di/src/main/java/team/aliens/_di/local/DataStorageModule.kt
> +    abstract fun provideAuthDataStorage(
좋아요

2023-04-11 13:07 UTC, JunJaBoy commented on local/src/main/java/team/aliens/local/room/common/RoomProperty.kt
> +        const val DbName = "dorm-database"
공식 예제 참조했어요

2023-04-12 03:20 UTC, chlgkdms requested changes

2023-04-12 03:21 UTC, chlgkdms approved these changes

2023-04-13 02:10 UTC, Tmdhoon2 approved these changes

2023-04-13 02:11 UTC, merged