🔀 :: (#369) 로그인 화면에서 메인 화면으로 진입할 시 앱이 튕기는 오류 수정 버전 배포
team-aliens/DMS-Android pull request #370
Opened 2023-04-06 23:33 UTC by JunJaBoy

## 개요
> #367 과 동일한 작업이며, 버전 업데이트만 존재합니다.

## 작업사항
- 

## 추가 로 할 말

2023-04-07 00:12 UTC, Tmdhoon2 requested changes

2023-04-07 00:12 UTC, Tmdhoon2 commented on presentation/src/main/java/team/aliens/dms_android/feature/mypage/MyPageScreen.kt
> -                            .clickable {
이 부분 정확히 어떤 문제였나요?? 코드 상으로는 단순히 함수를 한 번 더 거쳐서 동작하게 만든것 같아서 궁금해요

2023-04-07 00:51 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/mypage/MyPageScreen.kt
> -                            .clickable {
단순하게 함수를 잘못 넣어줬었어요..
상점이 없을 때에 비밀번호 변경 버튼 함수에 onSignOutButtonClick() 함수를 넣어서 그런거였어요

2023-04-08 22:46 UTC, Tmdhoon2 approved these changes

2023-04-12 13:57 UTC, merged