🔀 :: (#347) 로그인 스크린 토스트 구현
team-aliens/DMS-Android pull request #381
Opened 2023-04-15 06:18 UTC by Tmdhoon2

## 개요
> 로그인 스크린 토스트를 구현했습니다.

## 작업사항
- 디자인 시스템에 DormToast 추가
- 로그인 스크린 DormToast 구현

## 추가 로 할 말
- 최대한 생각해서 로직을 구현해보긴 했는데, 코드 리뷰를 받으면 좀 더 효율적인 로직이 나올 수 있을 것 같아, 우선 로그인 스크린만 작업했습니다.
- 로그인 스크린에서 구현 / 사용할 로직을 바탕으로 전체 스크린에서의 기존 rememberToast 를 DormToast 로 대체할 계획입니다.

2023-04-16 23:15 UTC, limsaehyun commented on design-system/src/main/java/team/aliens/design_system/toast/toast.kt
> +fun DormToast(
Toast라기보다는 SnackBar라는 표현이 조금 더 맞지 않을까요?

2023-04-16 23:15 UTC, limsaehyun commented on design-system/src/main/java/team/aliens/design_system/toast/toast.kt
> +        delay(3000)
토스트 시간은 default 값을 3000으로 하고,
사용자가 설정할 수 있게 하는거 어떤가요?

2023-04-16 23:15 UTC, limsaehyun commented on design-system/src/main/java/team/aliens/design_system/toast/toast.kt
> +fun DormToast(
Toast와 SnackBar는 다른 특징을 가지고 있는데,
해당 디자인은 SnackBar에 가까운 것 같네요

2023-04-16 23:17 UTC, limsaehyun commented on presentation/src/main/java/team/aliens/dms_android/feature/auth/login/LoginScreen.kt
> +    val setToastStates = { event: Event ->
해당 토스트를 띄우기 위해서 isShowToast, toastMessage, setToastStates 가 필요한 것 같은데 약간 번거로운 것 같아요.
toastMessage는 어쩔 수 있지만 isShowToast, setToastStates를 없엘 순 없을까요?

2023-04-16 23:25 UTC, Tmdhoon2 commented on design-system/src/main/java/team/aliens/design_system/toast/toast.kt
> +fun DormToast(
나름 iOS 분들이나 디자이너 분들은 스낵바라는 명칭보다는 토스트라고 많이 부르셔서 생각해본 네이밍이였는데, 스낵바가 좀 더 가까운 것 같네요!

2023-04-16 23:31 UTC, Tmdhoon2 commented on design-system/src/main/java/team/aliens/design_system/toast/toast.kt
> +        delay(3000)
흠.. 토스트 시간이 변경되어야 하는 상황이 있을까요??

2023-04-16 23:35 UTC, Tmdhoon2 commented on presentation/src/main/java/team/aliens/dms_android/feature/auth/login/LoginScreen.kt
> +    val setToastStates = { event: Event ->
전에도 말씀드렸듯이 기존 토스트와는 다른 방식으로 로직을 구성해야 해서 나름 생각해본 방법이였는데, 좀 더 고민하는 시간이 필요할 듯 하네요..

2023-04-17 00:27 UTC, Tmdhoon2 commented on presentation/src/main/java/team/aliens/dms_android/feature/auth/login/LoginScreen.kt
> +    val setToastStates = { event: Event ->
isShowToast 라는 파라미터 자체를 없애는 건 불가능할 것 같아요.. 왜냐면, 기존 토스트처럼 함수를 호출할 때 작동하는게 아니라, 뷰단에서 미리 배치를 해두고, 에러가 발생했는지 여부를 전달해야만 보여줄지 말지 결정할 수 있기 때문에 이 상태를 관리하는 변수가 있어야 할 것 같아요.
그리고 setToastStates 같은 경우는 편의 상 구현해준 함수라서 없앨 순 있지만 그렇게 되면 LaunchedEffect 의 이벤트 처리하는 부분에서 각각 따로 처리를 해줘야 해요

2023-04-17 11:17 UTC, limsaehyun commented on design-system/src/main/java/team/aliens/design_system/toast/toast.kt
> +fun DormToast(
기존 방식의 토스트가 사용되지 않는다면 괜찮을 것 같네요

2023-04-17 11:17 UTC, limsaehyun commented on design-system/src/main/java/team/aliens/design_system/toast/toast.kt
> +        delay(3000)
시간은 유연하게 가져가야 하는 부분이라고 생각합니다.
또는 지속시간에 대한 설정값을 부여해도 괜찮을 것 같네요

2023-04-24 02:20 UTC, JunJaBoy commented on design-system/src/main/java/team/aliens/design_system/icon/icons.kt
이 파일에 변경이 생긴 이유가 뭘까요?

2023-04-24 02:20 UTC, JunJaBoy commented on design-system/src/main/java/team/aliens/design_system/toast/toast.kt
> +        textColor = DormColor.DormPrimary,
`DormTheme` 사용해주세요

2023-04-24 02:20 UTC, JunJaBoy commented on design-system/src/main/java/team/aliens/design_system/toast/toast.kt
> +    isShowToast: MutableState<Boolean>,
shouldShowToast 사용하면 어떨까요? 의견입니다

2023-04-24 02:20 UTC, JunJaBoy commented on design-system/src/main/java/team/aliens/design_system/toast/toast.kt
> +    }
개발하면서 참고하신 원본 자료 있나요?

2023-04-24 02:20 UTC, JunJaBoy commented on design-system/src/main/java/team/aliens/design_system/toast/toast.kt
> +                    .height(48.dp)
여기 고정값 주면 안돼요..! 궁금하시면 에뮬 글자 크기 최대로 한 번 테스트해 보세요

2023-04-24 02:20 UTC, JunJaBoy commented on design-system/src/main/java/team/aliens/design_system/toast/toast.kt
> +                    ),
여기 onError가 background로 들어가있는 이유가 뭔가요?

2023-04-24 02:20 UTC, JunJaBoy commented on design-system/src/main/java/team/aliens/design_system/toast/toast.kt
> +                    modifier = Modifier.padding(bottom = 2.dp),
혹시 중앙정렬때문에 이렇게 하신건가요?

2023-04-24 02:20 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/auth/login/LoginScreen.kt
> +    val isShowToast = remember { mutableStateOf(false) }
shouldShowToast 어떤가요?

2023-04-24 02:20 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/auth/login/LoginScreen.kt
> +    var isPasswordError by remember { mutableStateOf(false) }
이거 좋지 못한 방법인 것 같아요

2023-04-25 01:20 UTC, JunJaBoy commented on design-system/src/main/java/team/aliens/design_system/toast/toast.kt
> +        textColor = DormColor.DormPrimary,
혹시 button에서는 어떻게 구현되어있나요? DormTheme 사용에 제약이 있다면 enum을 사용하는게 괜찮을지 모르겠네요

2023-04-25 01:21 UTC, JunJaBoy commented on design-system/src/main/java/team/aliens/design_system/toast/toast.kt
> +    isShowToast: MutableState<Boolean>,
isShowToast는 '토스트를 보여주는 것인지' 라는 뜻을 가지고 있지만, shouldShowToast는 '토스트를 보여야 하는지' 라는 뜻을 가지고 있어서 의미상 더 적합할 것 같아요

2023-04-25 01:22 UTC, JunJaBoy commented on design-system/src/main/java/team/aliens/design_system/toast/toast.kt
> +    }
여기에 delay를 두신 이유가 있나요?

2023-04-25 01:25 UTC, JunJaBoy commented on design-system/src/main/java/team/aliens/design_system/toast/toast.kt
> +                    .height(48.dp)
혹시 수정 하셨나요?

2023-04-25 01:25 UTC, JunJaBoy commented on design-system/src/main/java/team/aliens/design_system/toast/toast.kt
> +                    modifier = Modifier.padding(bottom = 2.dp),
좋지 못한 방법인 것 같아요.. 컴포즈 자체적인 typography 문제가 이전 버전에 있었는데, 컴포즈 버전 업데이트하면 해결될 수도 있으니 일단 지워주세요. 그리고 만약 글꼴 크기가 다르면 또 문제가 생길 수도 있을 것 같아요.

2023-04-25 01:26 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/auth/login/LoginScreen.kt
> +    var isPasswordError by remember { mutableStateOf(false) }
토스트를 각 스크린별로 관리하지 말고 최상위 컴포저블에 DormTheme()처럼 ToastLayout()으로 관리하고, `toast(error, message)` 이런 식으로 호출해야할 것 같아요

2023-04-25 01:38 UTC, Tmdhoon2 commented on presentation/src/main/java/team/aliens/dms_android/feature/auth/login/LoginScreen.kt
> +    var isPasswordError by remember { mutableStateOf(false) }
말씀해주신 방법은 좀 더 알아봐야할 것 같네용

2023-04-25 01:38 UTC, Tmdhoon2 commented on design-system/src/main/java/team/aliens/design_system/toast/toast.kt
> +                    modifier = Modifier.padding(bottom = 2.dp),
흠 알겠습니당

2023-04-25 01:38 UTC, Tmdhoon2 commented on design-system/src/main/java/team/aliens/design_system/toast/toast.kt
> +                    .height(48.dp)
넵 wrapContentHeight 로 수정 완료 했습니다

2023-04-25 01:38 UTC, Tmdhoon2 commented on design-system/src/main/java/team/aliens/design_system/toast/toast.kt
> +    }
토스트를 직접 가져다 사용하는 디자인 시스템 외부에서는 토스트 delay 에 관여하지 않게 하기 위해서 내부에서 delay 를 처리해주었습니다

2023-04-25 01:38 UTC, Tmdhoon2 commented on design-system/src/main/java/team/aliens/design_system/toast/toast.kt
> +        textColor = DormColor.DormPrimary,
버튼 컬러 enum 들도 DormTheme 가 아닌 DormColor 들들을 사용하고 있네요.. 토스트는 enum 에 들어가는 값이 많지 않아서 없애고 각각 주입받아도 괜찮지만, 버튼 방식을 바꾸게 된다면 영향 가는 곳이 많을 것 같네요

2023-04-25 01:44 UTC, JunJaBoy commented on design-system/src/main/java/team/aliens/design_system/toast/toast.kt
> +        textColor = DormColor.DormPrimary,
그럼 일단 버튼은 그냥 두고, 다른 예제 참고해서 ErrorToast(), DefaultToast() 등등 모두 컴포저블로 사용하도록 해주실 수 있나요? 계속 이렇게 관리하게 되면 언젠가 다크 테마에 따른 컬러 적용에 차질이 생길거에요

2023-04-25 01:44 UTC, JunJaBoy commented on design-system/src/main/java/team/aliens/design_system/toast/toast.kt
> +    }
delay가 무슨 의미인가요?

2023-04-25 01:45 UTC, Tmdhoon2 commented on design-system/src/main/java/team/aliens/design_system/toast/toast.kt
> +    isShowToast: MutableState<Boolean>,
으음 문법상 더 정확한 뜻을 담고 있는 쪽으로 생각하신거군요 
저는 보통 boolean 형 변수들은 Is~~ 로 표현하니까 좀 더 익숙하게 네이밍 하기 위해서 isShowToast 라는 이름을 선택했는데, 준수님 의견도 맞는 것 같네요

2023-04-25 01:46 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/auth/login/LoginScreen.kt
> +    var isPasswordError by remember { mutableStateOf(false) }
지금 로그인 스크린 토스트를 이렇게 구현하면, 다른 화면 모두 유사하게 구현하게 될 것 같아요. 가능하면 이번 작업에서 LoccalToast... 이런걸 만들거나 아예 스크린 적용을 하지 않도록 해야할 것 같네요

2023-04-25 01:47 UTC, Tmdhoon2 commented on design-system/src/main/java/team/aliens/design_system/toast/toast.kt
> +        textColor = DormColor.DormPrimary,
아하 알겠습니당

2023-04-25 01:51 UTC, Tmdhoon2 commented on presentation/src/main/java/team/aliens/dms_android/feature/auth/login/LoginScreen.kt
> +    var isPasswordError by remember { mutableStateOf(false) }
맞아요 로그인 스크린에서 작업한 토스트 로직을 전반적인 스크린에 적용하려 하긴 했는데.. 좀 더 나은 방법을 찾는게 맞는거 같아요

2023-04-25 01:55 UTC, Tmdhoon2 commented on design-system/src/main/java/team/aliens/design_system/toast/toast.kt
> +    }
코루틴 delay 함수인데... 음 질문의 의도가 혹시 뭔가여

2023-04-25 10:24 UTC, JunJaBoy commented on design-system/src/main/java/team/aliens/design_system/toast/toast.kt
> +        textColor = DormColor.DormPrimary,
셤 끝나고 다시 작업하죠

2023-04-25 10:24 UTC, JunJaBoy commented on design-system/src/main/java/team/aliens/design_system/toast/toast.kt
> +    isShowToast: MutableState<Boolean>,
결정해 주세요. 컨벤션 회의할 때 상의해봐야 할 것 같은데 아직 개발 단계이니 나중에 바꿔도 될 것 같아요

2023-04-25 10:25 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/auth/login/LoginScreen.kt
> +    var isPasswordError by remember { mutableStateOf(false) }
시험 끝나고 작업하죠

2023-04-27 06:54 UTC, aahspringaa4 commented
이건 언제 머지되나요

2023-04-27 07:15 UTC, Tmdhoon2 commented
> 이건 언제 머지되나요

내부 로직을 좀 더 개선한 후에 머지해야할 것 같습니다..

2023-04-29 13:17 UTC, JunJaBoy requested changes

2023-04-29 13:17 UTC, JunJaBoy commented on design-system/src/main/java/team/aliens/design_system/toast/toast.kt
> +    }
이 부분 이슈 남겨주세요

2023-04-29 13:17 UTC, JunJaBoy commented on design-system/src/main/java/team/aliens/design_system/toast/toast.kt
> +    duration: Long = 3000L,
`duration`은 DormToast에서도 default값을 주는 것 같네요

2023-04-29 13:17 UTC, JunJaBoy commented on design-system/src/main/java/team/aliens/design_system/toast/toast.kt
> +    duration: Long = 3000L,
@chlgkdms 토스트 표시 여부를 표현하는 변수 네이밍을 할 때, `isShowToast`가 좋나요 `shouldShowToast`가 좋나요?

2023-04-29 13:17 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/common/CompositionLocal.kt
> +    { _: String, _: ToastType -> Unit }
String 타입 `_`이랑 ToastType 타입 `_`이랑 의미하는게 뭔가요?

2023-04-29 13:17 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/common/CompositionLocal.kt
> +    { _: String, _: ToastType -> Unit }
이러한 방법을 시도하신 건 좋은데, 람다 특성상 사용하지 않는 리시버를 `_` 처리하도록 권장하나보네요.. 코드상에서 이를 노출시켜줘야 할 것 같아요

2023-04-29 13:17 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/common/CompositionLocal.kt
> +    { _: String, _: ToastType -> Unit }
compositionLocalOf<(`string타입 리시버명`: String, toastType: ToastType) -> Unit)> {} 이런것도 시도해보면 어떨까요?

2023-04-29 13:17 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/common/CompositionLocal.kt
> +    { _: String, _: ToastType -> Unit }
이 코드도 나중에 리팩토링하면서 갈릴 것 같긴 해요

2023-04-29 13:17 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/auth/login/LoginScreen.kt
로그인스크린 기존 토스트 코드 제거했나요?

2023-04-29 13:17 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/util/compose/Toast.kt
> +}
다같이 다시 얘기해보죠

2023-04-29 13:17 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/util/compose/Toast.kt
> +}
저번에 제가 승훈님께 요구한 사항은 로그인 스크린에서 새로 작성한 코드 제거만 말씀드리지 않았었나요?

2023-04-29 13:34 UTC, chlgkdms commented on design-system/src/main/java/team/aliens/design_system/toast/toast.kt
> +    duration: Long = 3000L,
제 생각에는 boolean 변수니 is를 사용하는게 좀 더 맞다고 생각합니다 예전에 변수 네이밍 규칙 찾아보다가 봤는데 boolean 변수는 is 접두사를 쓴다고 해서 is를 쓰는게 맞지 않나..싶네요

2023-04-29 13:50 UTC, Tmdhoon2 commented on presentation/src/main/java/team/aliens/dms_android/feature/auth/login/LoginScreen.kt
함수 호출 관련 문제 해결중이라서 아직 제거하진 않았습니다

2023-04-29 13:52 UTC, Tmdhoon2 commented on presentation/src/main/java/team/aliens/dms_android/util/compose/Toast.kt
> +}
음 최상위 레이아웃에 토스트 함수 선언해놓는 방식으로 처리해보라고 하시지 않으셨나요??...

2023-04-29 14:09 UTC, Tmdhoon2 commented on presentation/src/main/java/team/aliens/dms_android/common/CompositionLocal.kt
> +    { _: String, _: ToastType -> Unit }
지금 당장은 변수 이름만 명시해주는게 최선인거 같네용

2023-04-30 01:11 UTC, Tmdhoon2 commented on design-system/src/main/java/team/aliens/design_system/toast/toast.kt
> +    isShowToast: MutableState<Boolean>,
그럼 일단은 isShowToast 로 가고 컨벤션 회의 때 한 번 결정하는걸로 해도 될까요??

2023-04-30 01:26 UTC, Tmdhoon2 commented on presentation/src/main/java/team/aliens/dms_android/common/CompositionLocal.kt
> +    { _: String, _: ToastType -> Unit }
> 이 코드도 나중에 리팩토링하면서 갈릴 것 같긴 해요

따로 생각하신 로직이 있다는 말씀이신가요?

2023-04-30 12:34 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/common/CompositionLocal.kt
> +    { toastMessage: String, toastType: ToastType -> Unit }
이러면 린트 오류 나지 않나요?

2023-04-30 12:34 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/util/compose/Toast.kt
> +            message, toastType,
혹시 이렇게 사용하실거면 파라미터 네임 붙여주세요

2023-04-30 12:34 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/util/compose/Toast.kt
> +            message, toastType,
```suggestion
            toastMessage = message,
            toastType = toastType,
```

2023-04-30 14:08 UTC, JunJaBoy approved these changes

2023-04-30 14:09 UTC, chlgkdms approved these changes

2023-05-01 02:30 UTC, closed without merging