🔀 :: (#382) usecase 재구성 및 통합
team-aliens/DMS-Android pull request #383
Opened 2023-04-18 06:04 UTC by JunJaBoy

## 개요
> usecase의 이름 및 파라미터를 변경합니다

## 작업사항
- UseCase의 네이밍을 수정합니다
- UseCase의 패키지 경로를 수정합니다
- UseCase를 사용하는 Presentation의 파라미터를 변경합니다
- UseCase<I, O> abstract class를 Deperecated합니다

## 추가 로 할 말

2023-04-18 11:00 UTC, Tmdhoon2 requested changes

2023-04-18 23:27 UTC, JunJaBoy commented on data/src/main/java/team/aliens/data/_datasource/remote/RemoteStudyRoomDataSource.kt
> +import java.util.UUID
넹

2023-04-18 23:28 UTC, JunJaBoy commented on design-system/src/main/java/team/aliens/design_system/component/notice.kt
>          Notice(
저도 그 의견 동의합니다. Preview는 Design System에만 있어도 된다고 생각하고, Preview를 만들어도 미리보기 오류가 가끔 있어서 빼는게 좋을 것 같아요

2023-04-18 23:35 UTC, JunJaBoy commented on remote/src/main/java/team/aliens/remote/service/StudentService.kt
> +    ): Response<Unit>
앗 테스트 했습니다

2023-04-18 23:36 UTC, JunJaBoy commented on remote/src/main/java/team/aliens/remote/http/FileUploadClient.kt
> +class FileUploadClient @Inject constructor() : OkHttpClient() {
hilt dependency 그래프에 객체를 등록할 때, 그러니까 어떤 객체를 주입받거나 주입해 줄 때, 생성자에 @Inject 애너테이션을 붙여서 표현합니다

2023-04-18 23:38 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/viewmodel/mypage/MyPageViewModel.kt
>      sealed class Event {
엥 이건 제가 작업한 부분이 아니어서..

2023-04-18 23:38 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/viewmodel/mypage/MyPageViewModel.kt
>      sealed class Event {
그리고 어떤 네이밍 규칙을 말씀하시는건지 잘 모르겠네요

2023-04-18 23:41 UTC, Tmdhoon2 commented on remote/src/main/java/team/aliens/remote/http/FileUploadClient.kt
> +class FileUploadClient @Inject constructor() : OkHttpClient() {
지금 코드상으로 FileUploadClient 에는 다른 객체가 주입되지 않는 것 같아서 말씀드린거에용

2023-04-18 23:44 UTC, Tmdhoon2 commented on presentation/src/main/java/team/aliens/dms_android/viewmodel/mypage/MyPageViewModel.kt
>      sealed class Event {
아하 확인했습니당

2023-04-18 23:45 UTC, JunJaBoy commented on remote/src/main/java/team/aliens/remote/common/HttpPath.kt
> +        const val CancelSeat = "/${Companion.StudyRooms}/$Seats/{seat-id}"
아 넵 이 부분은 많이 생각해 봤어요

2023-04-18 23:46 UTC, JunJaBoy commented on remote/src/main/java/team/aliens/remote/common/HttpPath.kt
> +        const val CancelSeat = "/${Companion.StudyRooms}/$Seats/{seat-id}"
조금만 이따.. 관리해 보려고요

2023-04-18 23:46 UTC, JunJaBoy commented on remote/src/main/java/team/aliens/remote/common/HttpPath.kt
> +        const val CancelSeat = "/${Companion.StudyRooms}/$Seats/{seat-id}"
일단 이슈 등록해 둘테니 하은이 시키죠 ????!! @chlgkdms

2023-04-18 23:49 UTC, JunJaBoy commented on remote/src/main/java/team/aliens/remote/http/IgnoreRequestWrapper.kt
> +object IgnoreRequestWrapper {
네네 맞아요

2023-04-18 23:49 UTC, JunJaBoy commented on domain/src/main/java/team/aliens/domain/_model/_common/Sex.kt
>      ;
혹시 어떤 컨벤션 말씀하시는건가요?

2023-04-18 23:51 UTC, Tmdhoon2 commented on domain/src/main/java/team/aliens/domain/_model/_common/Sex.kt
>      ;
이제 뭐 개행이라던가... 세미콜론이라던가..

2023-04-18 23:52 UTC, JunJaBoy commented on domain/src/main/java/team/aliens/domain/usecase/auth/CheckEmailVerificationCodeUseCase.kt
> +    suspend operator fun invoke(
왜 그렇게 생각하시나요?

2023-04-18 23:52 UTC, JunJaBoy commented on domain/src/main/java/team/aliens/domain/usecase/auth/CheckEmailVerificationCodeUseCase.kt
> +    suspend operator fun invoke(
이전에도 말씀드렸던 것 같은데, Http 요청을 보낼 때를 기준으로, JSON Body를 구현해야할 경우에만 Input 클래스를 사용하면 좋을 것 같아요. PathVariable, Query String과의 구분도 쉽게 될거고..

2023-04-18 23:52 UTC, JunJaBoy commented on domain/src/main/java/team/aliens/domain/usecase/auth/CheckEmailVerificationCodeUseCase.kt
> +    suspend operator fun invoke(
어떻게 생각하세요? @chlgkdms

2023-04-18 23:52 UTC, JunJaBoy commented on domain/src/main/java/team/aliens/domain/usecase/notice/FetchNoticesUseCase.kt
> +        order: Order,
저도 Notice~ 고민 많이 했는데, 만약 다른 시간 기준 정렬 기능이 필요한 기능이 추가되는 경우에도 재활용하기 위해서 Order로 명명해 두었어요. NoticeOrder을 사용해야 하는 이유가 무엇이라고 생각하시나요? @chlgkdms

2023-04-18 23:56 UTC, JunJaBoy commented on domain/src/main/java/team/aliens/domain/usecase/student/FindIdUseCase.kt
> +        schoolId: UUID,
앗 맨 위쪽 답변 확인해 주세여

2023-04-18 23:57 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/auth/changepassword/ChangePasswordVerifyEmailScreen.kt
> +                            type = SendEmailVerificationCodeInput.SendEmailVerificationCodeType.PASSWORD,
ㅇㅎ 사실 무지성 tab 누르다가 발생한 일이긴 한데, Import하면 해결할 수 있어요. 나중에 Screen 리팩토링 할 때 고치는거로 하죠

2023-04-18 23:58 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/auth/findid/FindIdScreen.kt
> +                    )
엥 이건 코드 자동 정렬하다 그랬던 것 같긴 해요

2023-04-18 23:59 UTC, JunJaBoy commented on domain/src/main/java/team/aliens/domain/_model/_common/Sex.kt
>      ;
ㅇㅎㅇㅎ 좋네여

2023-04-19 00:00 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/auth/findid/FindIdViewModel.kt
>      internal fun findId(schoolId: UUID, name: String, grade: Int, classRoom: Int, number: Int) {
넵 Screen 리팩토링때 하도록 하죠

2023-04-19 00:00 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/cafeteria/MealContent.kt
> +        state.meals.collect {
아 좋아여

2023-04-19 00:02 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/notice/NoticeScreen.kt
>                      }
제가 작성한 코드가 아니긴 한데, 만약 승훈님이 하신 방법대로 하면, 기존 코드에선 1번 인덱스부터 참조하고 있지만 승훈님은 0번째 인덱스부터 접근하려 해서 IndexOutOfBoundsException이 발생할 것 같아요. 물론 코드상으로 어떻게 되어있는지 자세히는 모르겠네요..;

2023-04-19 00:03 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/register/ui/email/SignUpEmailVerifyScreen.kt
> +                    type = EmailVerificationType.SIGNUP,
아 실제로 보면 뭔가 안에가 다르더라고요..?

2023-04-19 00:03 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/register/ui/email/SignUpEmailVerifyScreen.kt
> +                    type = EmailVerificationType.SIGNUP,
그래서 이렇게 두었습니다..

2023-04-19 00:04 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/register/ui/email/SignUpEmailVerifyScreen.kt
> +                    type = EmailVerificationType.SIGNUP,
엥 같네요

2023-04-19 00:05 UTC, Tmdhoon2 commented on domain/src/main/java/team/aliens/domain/usecase/notice/FetchNoticesUseCase.kt
> +        order: Order,
저는 지금 코드에서는 Order 라는 클래스가 Notice 관련 함수에서만 사용되고 있고, 추후에 다른 함수에서도 사용하게 된다면 그때 맞는 네이밍으로 바꿔도 괜찮을 것 같다는 입장이에요

2023-04-19 00:11 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/register/ui/email/SignUpEmailVerifyScreen.kt
> +                    )
이건 나중에 Screen 리팩토링할 때 다시 얘기하죠

2023-04-19 00:12 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/register/ui/last/SignUpPolicyScreen.kt
> +                            schoolVerificationCode = getString("schoolCode").toString(),
음.. 사실 이건 사라져야 하긴 해요

2023-04-19 00:12 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/register/ui/last/SignUpPolicyScreen.kt
> +                            schoolVerificationCode = getString("schoolCode").toString(),
ViewModel로 값들을 관리하기로 했죠..?

2023-04-19 00:13 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/studyroom/StudyRoomDetailScreen.kt
> +fun FetchSeatTypesOutput.SeatTypeInformation.toModel() = SeatTypeUiModel(
아뇨 중간에 끊겼어요

2023-04-19 00:13 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/studyroom/StudyRoomDetailScreen.kt
> +fun FetchSeatTypesOutput.SeatTypeInformation.toModel() = SeatTypeUiModel(
이건 기존 코드에서 클래스만 변경한 거에요

2023-04-19 00:14 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/viewmodel/changepw/ChangePasswordViewModel.kt
> +        data class CheckIdSuccess(val email: String) : Event()
좋아요

2023-04-19 00:17 UTC, Tmdhoon2 commented on presentation/src/main/java/team/aliens/dms_android/feature/notice/NoticeScreen.kt
>                      }
흠.. 알겠습니당 여긴 제가 한 번 살펴볼게요

2023-04-19 00:18 UTC, Tmdhoon2 commented on presentation/src/main/java/team/aliens/dms_android/feature/register/ui/last/SignUpPolicyScreen.kt
> +                            schoolVerificationCode = getString("schoolCode").toString(),
아하 그렇네요

2023-04-19 00:18 UTC, Tmdhoon2 commented on presentation/src/main/java/team/aliens/dms_android/feature/studyroom/StudyRoomDetailScreen.kt
> +fun FetchSeatTypesOutput.SeatTypeInformation.toModel() = SeatTypeUiModel(
아하 확인했습니당

2023-04-19 04:29 UTC, chlgkdms requested changes

2023-04-19 04:50 UTC, JunJaBoy commented on domain/src/main/java/team/aliens/domain/usecase/notice/FetchNoticesUseCase.kt
> +        order: Order,
지금 NoticeOrder로 바꾸고, 만약 나중에 필요하다면 다시 Order로 바꾸는건 불필요한 비용 아닐까요? 차라리 정렬 옵션 중 시간에 관련된 정렬이니 TimeOrder 이런 식으로 가면 그때 가서 재활용도 되고, 의미상으로도 괜찮을 것 같은데 어케 생각하시나여?

2023-04-19 04:51 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/cafeteria/MealState.kt
> +    var meals: MutableStateFlow<FormedMeal> = MutableStateFlow(FormedMeal()),
Screen 레이어 리팩토링 진행하면서 domain, data에 이어서 presentation model까지 구성해야 합니다. 각 계층별로 사용되는 모델의 용도가 다르니까요

2023-04-19 05:13 UTC, Tmdhoon2 requested changes

2023-04-21 10:28 UTC, Tmdhoon2 requested changes

2023-04-21 10:28 UTC, Tmdhoon2 commented on presentation/src/main/java/team/aliens/dms_android/viewmodel/auth/register/school/ConfirmSchoolViewModel.kt
> +                )
```suggestion
                fetchSchoolVerificationQuestionUseCase(
                    fetchSchoolVerificationQuestionInput = FetchSchoolVerificationQuestionInput(
                        schoolId = schoolId,
                    ),
                )
```

2023-04-21 10:28 UTC, Tmdhoon2 commented on presentation/src/main/java/team/aliens/dms_android/viewmodel/home/MealViewModel.kt
> +                println("TESTTEST UPDATE $it")
로그 지워주세요

2023-04-21 10:28 UTC, Tmdhoon2 commented on presentation/src/main/java/team/aliens/dms_android/viewmodel/mypage/MyPageViewModel.kt
> +                )
```suggestion
                remotePointListUseCase(
                    fetchPointsInput = FetchPointsInput(
                        type = pointType,
                    ),
                )
```

2023-04-21 10:28 UTC, Tmdhoon2 commented on presentation/src/main/java/team/aliens/dms_android/viewmodel/notice/NoticeViewModel.kt
> +                )
```suggestion
                fetchNoticesUseCase(
                    fetchNoticesInput = FetchNoticesInput(
                        order = state.value.type,
                    ),
                )
```

2023-04-21 10:28 UTC, Tmdhoon2 commented on presentation/src/main/java/team/aliens/dms_android/viewmodel/notice/NoticeViewModel.kt
> +                )
```suggestion
                fetchNoticeDetailsUseCase(
                    fetchNoticeDetailsInput = FetchNoticeDetailsInput(
                        noticeId = noticeId,
                    ),
                )
```

2023-04-21 10:28 UTC, Tmdhoon2 commented on presentation/src/main/java/team/aliens/dms_android/viewmodel/remain/RemainApplicationViewModel.kt
> +                )
```suggestion
                updateRemainOptionUseCase(
                    updateRemainsOptionInput = UpdateRemainsOptionInput(
                        remainsOptionId = state.value.remainOptionId,
                    ),
                )
```

2023-04-21 10:28 UTC, Tmdhoon2 commented on presentation/src/main/java/team/aliens/dms_android/viewmodel/studyroom/StudyRoomDetailsViewModel.kt
> +                    ApplySeatInput(
```suggestion
                    applySeatInput = ApplySeatInput(
```

2023-04-21 10:28 UTC, Tmdhoon2 commented on presentation/src/main/java/team/aliens/dms_android/viewmodel/studyroom/StudyRoomDetailsViewModel.kt
> +                    CancelSeatInput(
```suggestion
                    cancelSeatInput = CancelSeatInput(
```

2023-04-21 10:28 UTC, Tmdhoon2 commented on presentation/src/main/java/team/aliens/dms_android/viewmodel/studyroom/StudyRoomDetailsViewModel.kt
> +                    FetchStudyRoomDetailsInput(
```suggestion
                    fetchStudyRoomDetailsInput = FetchStudyRoomDetailsInput(
```

2023-04-21 10:28 UTC, Tmdhoon2 commented on presentation/src/main/java/team/aliens/dms_android/viewmodel/studyroom/StudyRoomDetailsViewModel.kt
> +                    FetchSeatTypesInput(
```suggestion
                    fetchSeatTypesInput = FetchSeatTypesInput(
```

2023-04-21 10:28 UTC, Tmdhoon2 commented on presentation/src/main/java/team/aliens/dms_android/widget/meal/MealService.kt
> +            )
```suggestion
            fetchMealsUseCase(
                fetchMealsInput = FetchMealsInput(
                    date = nowDate,
                ),
            )
```

2023-04-21 10:28 UTC, Tmdhoon2 commented on presentation/src/main/java/team/aliens/dms_android/widget/meal/provider/BaseMealWidgetProvider.kt
> +            )
```suggestion
            fetchMealsUseCase(
                fetchMealsInput = FetchMealsInput(
                    date = nowDate,
                ),
            )
```

2023-04-21 21:48 UTC, JunJaBoy commented on data/src/main/java/team/aliens/data/_datasource/remote/RemoteStudyRoomDataSource.kt
> +        studyRoomId: UUID,
음.. 아마 Outdated되어서 그런 것 같네요 새로고침하면 괜찮아질듯

2023-04-21 23:15 UTC, Tmdhoon2 approved these changes

2023-04-22 04:16 UTC, chlgkdms approved these changes

2023-04-22 04:34 UTC, merged