🔀 :: (#393) 상벌점 상세 조회 screen 리팩토링
team-aliens/DMS-Android pull request #404
Opened 2023-05-06 12:56 UTC by chlgkdms

## 개요
> 상벌점 상세 조회 screen 리팩토링을 했습니다.

## 작업사항
- 상벌점, 전체 string 추가를 했습니다.
- viewmodel에 event 추가를 했습니다.
- PointListScreen Button 재사용성을 높여서 다시 구현했습니다.

## 추가 로 할 말

2023-05-06 13:06 UTC, limsaehyun commented on presentation/src/main/java/team/aliens/dms_android/feature/pointlist/PointListScreen.kt
> +                println(selectedType)
println의 목적이 뭔가요?

2023-05-06 13:06 UTC, limsaehyun commented on presentation/src/main/java/team/aliens/dms_android/feature/pointlist/PointListScreen.kt
> +val pointListButtons = arrayListOf(
private 처리 해도 되는 부분같아요~

2023-05-06 13:06 UTC, limsaehyun commented on presentation/src/main/java/team/aliens/dms_android/feature/pointlist/PointListScreen.kt
> +                when (button.type) {
`myPageViewModel.fetchPointList(button.type)`

하면 안될까요?
반복되는 구조 같아서요

2023-05-06 13:13 UTC, chlgkdms commented on presentation/src/main/java/team/aliens/dms_android/feature/pointlist/PointListScreen.kt
> +                println(selectedType)
헉 테스트 하다가 안 지웠나봐요 ㅠㅠ 삭제하겠습니다!

2023-05-06 13:18 UTC, chlgkdms commented on presentation/src/main/java/team/aliens/dms_android/feature/pointlist/PointListScreen.kt
> +                when (button.type) {
수정하겠습니다!

2023-05-06 13:23 UTC, chlgkdms commented on presentation/src/main/java/team/aliens/dms_android/feature/pointlist/PointListScreen.kt
> +                text = when (button.type) {
수정했습니다!

2023-05-06 13:58 UTC, Tmdhoon2 requested changes

2023-05-06 13:58 UTC, Tmdhoon2 commented on presentation/src/main/java/team/aliens/dms_android/feature/pointlist/PointListScreen.kt
> +                text = when (button.type) {
string resource 반환하는 형식의 when 문이 밑에 코드에서도 쓰인 것 같은데 따로 함수로 빼놓으면 좋을 것 같아요

2023-05-06 13:58 UTC, Tmdhoon2 commented on presentation/src/main/java/team/aliens/dms_android/feature/pointlist/PointListScreen.kt
> +                        ""
여기 else 꼭 있어야 하나요??

2023-05-06 14:08 UTC, chlgkdms commented on presentation/src/main/java/team/aliens/dms_android/feature/pointlist/PointListScreen.kt
> +                        ""
그 stringresource를 따로 빼면서 else가 사라지긴 했어요

2023-05-06 14:10 UTC, chlgkdms commented on presentation/src/main/java/team/aliens/dms_android/feature/pointlist/PointListScreen.kt
> +                text = when (button.type) {
빼려고 했는데 빼기가 좀 애매한 것 같아서 냅두고 있었어요..!

2023-05-06 14:17 UTC, chlgkdms commented on presentation/src/main/java/team/aliens/dms_android/feature/pointlist/PointListScreen.kt
> +                text = when (button.type) {
함수로 뺐습니다!

2023-05-07 11:44 UTC, JunJaBoy requested changes

2023-05-07 11:44 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/pointlist/PointListScreen.kt
> +)
버튼같은 사이즈는 고정값을 가지게 되면 글씨 크기에 따라서 유동적으로 변하지 않아요. font에 sp를 쓰는 의미가 없어지게 되어서, 지양하는 편이 좋을 것 같네요

2023-05-07 11:44 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/pointlist/PointListScreen.kt
> +fun PointRadioButton(
PointRadioButton이라는 네이밍이 적절하지 않은 듯 하네요

2023-05-07 11:44 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/pointlist/PointListScreen.kt
> +fun PointRadioButton(
RadioGroup을 래핑하는 함수같은데, 상의해서 다시 네이밍을 해야할 것 같네요

2023-05-07 11:44 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/pointlist/PointListScreen.kt
> +        Modifier.padding(start = 24.dp, top = 50.dp),
아규먼트 네임을 뺀 이유가 있나요?

2023-05-07 11:44 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/pointlist/PointListScreen.kt
> +    selectedType: PointType,
~RadioGroup이라는 네이밍이 적합해 보이네요

2023-05-07 11:44 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/pointlist/PointListScreen.kt
> +    selectedType: PointType,
그리고 이 컴포넌트는 디자인시스템으로 뺴는게 좋을 것 같아요

2023-05-07 11:44 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/pointlist/PointListScreen.kt
> +                    }
트레일링 컴마 붙여주세요

2023-05-07 13:19 UTC, chlgkdms commented on presentation/src/main/java/team/aliens/dms_android/feature/pointlist/PointListScreen.kt
> +        Modifier.padding(start = 24.dp, top = 50.dp),
왜 빠졌지.. 수정했습니다!

2023-05-10 02:19 UTC, Tmdhoon2 requested changes

2023-05-10 02:19 UTC, Tmdhoon2 commented on presentation/src/main/java/team/aliens/dms_android/feature/pointlist/PointListScreen.kt
> +                    id = when (button.type) {
이 부분 함수로 빼는건 어떻게 되었나요

2023-05-10 02:48 UTC, chlgkdms commented on presentation/src/main/java/team/aliens/dms_android/feature/pointlist/PointListScreen.kt
> +                    id = when (button.type) {
그거 지금 로컬에 작업 해놨고 커밋 하겠습니당

2023-05-10 07:43 UTC, chlgkdms commented on presentation/src/main/java/team/aliens/dms_android/feature/pointlist/PointListScreen.kt
> +fun PointRadioButton(
어떤식으로 네이밍하면 좋을까요...

2023-05-10 08:16 UTC, Tmdhoon2 requested changes

2023-05-10 08:42 UTC, JunJaBoy requested changes

2023-05-10 08:42 UTC, JunJaBoy commented on design-system/src/main/java/team/aliens/design_system/button/basicbutton.kt
> +//private val BasicLargeButtonHeight = 40.dp
주석 제거해주세요

2023-05-10 08:42 UTC, JunJaBoy commented on design-system/src/main/java/team/aliens/design_system/button/basicbutton.kt
> +            vertical = 9.dp,
이 패딩값도 stable 상수로 선언하고 전달해주었으면 하네요

2023-05-10 09:10 UTC, JunJaBoy approved these changes

2023-05-10 09:44 UTC, merged