Feature/405 baseviewmodel 구현
team-aliens/DMS-Android pull request #408
Opened 2023-05-11 09:43 UTC by JunJaBoy

## 개요
> Base ViewModel인 `MviViewModel` 클래스를 구현합니다

## 작업사항
- MviViewModel 구현
- UiEvent, UiState 네이밍 정정
- Reducer 구현

## 추가 로 할 말
제 코드 설명에도 이해가 안되시면 아래 블로그를 참고해 주세요!
### 참고 자료
- https://medium.com/@VolodymyrSch/android-simple-mvi-implementation-with-jetpack-compose-5ee5d6fc4908

2023-05-11 14:27 UTC, Tmdhoon2 requested changes

2023-05-11 14:27 UTC, Tmdhoon2 commented on presentation/src/main/java/team/aliens/dms_android/feature/studyroom/StudyRoomDetailsViewModel.kt
> +    sealed class UiEvent : team.aliens.dms_android._base.UiEvent {
여기 한 번 확인해주세요

2023-05-11 14:27 UTC, Tmdhoon2 commented on presentation/src/main/java/team/aliens/dms_android/feature/studyroom/StudyRoomListViewModel.kt
> +    sealed class UiEvent : team.aliens.dms_android._base.UiEvent {
여기도 import 한 번 확인해주세요

2023-05-11 14:27 UTC, Tmdhoon2 commented on presentation/src/main/java/team/aliens/dms_android/_base/MviViewModel.kt
> +    fun onEvent(event: E) {
여기 접근제한 없어도 될까용

2023-05-11 22:15 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/studyroom/StudyRoomDetailsViewModel.kt
> +    sealed class UiEvent : team.aliens.dms_android._base.UiEvent {
아마 이름 변경하면서 발생한 실수같은데, 이 스크린 리팩토링할 때 다시 확인하면 어떨까요?

2023-05-11 22:15 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/_base/MviViewModel.kt
> +    fun onEvent(event: E) {
넵 아마 클래스가 internal이어서, 어차피 presentation 모듈 안에서밖에 호출 못 해요

2023-05-13 02:42 UTC, chlgkdms approved these changes

2023-05-13 07:10 UTC, Tmdhoon2 commented on presentation/src/main/java/team/aliens/dms_android/feature/studyroom/StudyRoomDetailsViewModel.kt
> +    sealed class UiEvent : team.aliens.dms_android._base.UiEvent {
넵 그렇게 해도 될 것 같네요

2023-05-13 07:13 UTC, Tmdhoon2 requested changes

2023-05-13 07:13 UTC, Tmdhoon2 commented on presentation/src/main/java/team/aliens/dms_android/_base/MviViewModel.kt
> +        events.receiveAsFlow()
혹시 여기 부분 설명 부탁드려도 될까요??

2023-05-13 07:46 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/_base/MviViewModel.kt
> +        events.receiveAsFlow()
채널인 이벤트를 플로우로 변환하는 코드입니다. 함수명 그대로에요

2023-05-13 07:48 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/_base/MviViewModel.kt
> +        events.receiveAsFlow()
채널을 생성만 하고 구독(receive)하는 코드입니다. 구독을 하는 콜백으로 updateState 함수의 리플렉션을 인자로 전달하고, viewModelScope에서 콜백을 수행하도록 합니다.

2023-05-14 10:47 UTC, chlgkdms approved these changes

2023-05-14 10:48 UTC, Tmdhoon2 approved these changes

2023-05-14 10:50 UTC, merged