🔀 :: (#406) dmsappstate 구현
team-aliens/DMS-Android pull request #409
Opened 2023-05-14 23:31 UTC by Tmdhoon2

## 개요
> 앱 전역 상태 관리를 위한 DmsAppState 및 rememberDmsAppState() 를 구현하였습니다.

## 작업사항
- rememberDmsAppState() 구현
- 내부 showToast() 및 navigateToRoute() 구현
- 내부 setDialogState() 구현

## 추가 로 할 말

2023-05-14 23:37 UTC, JunJaBoy requested changes

2023-05-14 23:37 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/application/DmsAppState.kt
> +}
함수 말고 클래스 자체에 접근제한자를 붙이는게 좋을 것 같아요

2023-05-14 23:37 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/application/DmsAppState.kt
> +        this.dialogState.value = dialogState
이렇게 값을 변경하면 appstate가 변경될 때마다 컴포저블에서 액션을 취할 수 있나요? 생산자와 소비자 패턴이 생길 수 없을 것 같은데..

2023-05-15 12:42 UTC, JunJaBoy approved these changes

2023-05-15 12:43 UTC, chlgkdms approved these changes

2023-05-15 12:46 UTC, merged