🔀 :: (#407) 자습실 패키지 screen 리팩토링
team-aliens/DMS-Android pull request #410
Opened 2023-05-15 23:43 UTC by chlgkdms

## 개요
> 자습실 패키지 screen 리팩토링을 합니다.

## 작업사항
- string 수정
- screen 함수 분리 작업
- 예외 처리 rebase한 코드로 수정

## 추가 로 할 말

2023-05-16 01:13 UTC, Tmdhoon2 requested changes

2023-05-16 01:13 UTC, Tmdhoon2 commented on presentation/src/main/java/team/aliens/dms_android/feature/studyroom/StudyRoomDetailsScreen.kt
> +    val scope = rememberCoroutineScope()
상위 컴포저블 함수에서 선언하고 파라미터로 전달 받는게 좋을 것 같아요

2023-05-16 01:13 UTC, Tmdhoon2 commented on presentation/src/main/java/team/aliens/dms_android/feature/studyroom/StudyRoomDetailsScreen.kt
> +                CancelButton(
음 버튼 하나를 컴포저블 함수 단위로 나누는건 다시 생각해보는게 좋을 것 같아요

2023-05-16 01:13 UTC, Tmdhoon2 commented on presentation/src/main/java/team/aliens/dms_android/feature/studyroom/StudyRoomDetailsScreen.kt
> +        scope.launch {
여기 혹시 스코프가 필요한 이유가 뭔가요??

2023-05-16 01:39 UTC, chlgkdms commented on presentation/src/main/java/team/aliens/dms_android/feature/studyroom/StudyRoomDetailsScreen.kt
> +        scope.launch {
전에 있던 코드를 함수로 뺀 거라 제가 작성한 코드는 아니긴해요

2023-05-16 10:27 UTC, Tmdhoon2 commented on presentation/src/main/java/team/aliens/dms_android/feature/studyroom/StudyRoomDetailsScreen.kt
> +        scope.launch {
확인해서 scope 없어도 돌아가는 코드면 제거하는게 좋을 것 같네요

2023-05-16 23:24 UTC, chlgkdms commented on presentation/src/main/java/team/aliens/dms_android/feature/studyroom/StudyRoomDetailsScreen.kt
> +                CancelButton(
리뷰 반영 해서 코드 수정 완료했습니다!

2023-05-16 23:24 UTC, chlgkdms commented on presentation/src/main/java/team/aliens/dms_android/feature/studyroom/StudyRoomDetailsScreen.kt
> +        scope.launch {
제거했습니다!

2023-05-16 23:25 UTC, chlgkdms commented on presentation/src/main/java/team/aliens/dms_android/feature/studyroom/StudyRoomDetailsScreen.kt
> +    val scope = rememberCoroutineScope()
코드 수정 했습니다

2023-05-17 02:54 UTC, Tmdhoon2 requested changes

2023-05-17 02:56 UTC, chlgkdms commented on presentation/src/main/java/team/aliens/dms_android/feature/studyroom/StudyRoomDetailsScreen.kt
> +            onCancel
넵 작동됩니다

2023-05-17 02:58 UTC, Tmdhoon2 approved these changes

2023-05-17 23:21 UTC, JunJaBoy approved these changes

2023-05-17 23:21 UTC, merged