🔀 :: (#406) dmsappstate 구현
team-aliens/DMS-Android pull request #412
Opened 2023-05-16 13:21 UTC by Tmdhoon2

## 개요
> toastmanager 내부 로직 및 dialog manager 를 구현했습니다.

## 작업사항
- toast state flow 구현
- dialog manager 구현
- toast manager manager 패키지로 이동

## 추가 로 할 말
- dialog manager 추가적인 구현이 필요하여 이슈를 남겨놓았습니다.

2023-05-16 23:23 UTC, chlgkdms requested changes
지금 ci 안되는 것 같아요

2023-05-17 00:09 UTC, chlgkdms approved these changes

2023-05-18 01:30 UTC, JunJaBoy approved these changes

2023-05-18 01:30 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/util/manager/DialogManager.kt
> +    val onSubBtnClick: (() -> Unit)?,
```suggestion
    val onSubBtnClick: () -> Unit = {},
```

2023-05-18 01:30 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/util/manager/DialogManager.kt
> +    val onSubBtnClick: (() -> Unit)?,
이렇게 작성하면 버튼 로직이 필요 없을 것 같긴 한데..

2023-05-18 01:31 UTC, JunJaBoy commented
수고하셨어요. 아직 작업 끝나지 않았으니까, 지금 작업하신 모든 파일에 TODO 주석 달아주시고, 혹시 이슈 남기지 않으셨다면 이슈도 남겨주세요.

2023-05-18 01:41 UTC, Tmdhoon2 commented
> 수고하셨어요. 아직 작업 끝나지 않았으니까, 지금 작업하신 모든 파일에 TODO 주석 달아주시고, 혹시 이슈 남기지 않으셨다면 이슈도 남겨주세요.

주석 추가 했습니다. 코멘트 확인하시면 머지할게요

2023-05-18 02:02 UTC, merged