🔀 :: (#413) noticeviewmodel 리팩토링
team-aliens/DMS-Android pull request #419
Opened 2023-05-19 13:30 UTC by Tmdhoon2

## 개요
> notice view model 을 MviViewModel 을 상속받아서 재구현 했습니다

## 작업사항
- NoticeList -> Notices 로 네이밍 변경
- 새 NoticesViewModel 예외 처리 빼고 구현해서 주석처리 -> @JunJaBoy 
- NoticeEvent, NoticeState -> UiEvent, UiState 상속
- 수정 필요한 NoticesScreen 에 TODO 작성

## 추가 로 할 말
- @JunJaBoy -> 뷰모델 관련 예외 작업 완료되면 추가로 NoticesViewModel 작업 진행할 예정입니다

2023-05-19 14:12 UTC, chlgkdms requested changes

2023-05-19 14:12 UTC, chlgkdms commented on presentation/src/main/java/team/aliens/dms_android/feature/notice/NoticesViewModel.kt
> +}*/
위에 주석은 왜 남겨놨나요??

2023-05-20 03:16 UTC, Tmdhoon2 commented on presentation/src/main/java/team/aliens/dms_android/feature/notice/NoticesViewModel.kt
> +}*/
주석 처리된 부분이 새 MviViewmodel 적용한 뷰모델인데, 예외 처리 부분을 제외하고 구현하여 우선 구 뷰모델로 빌드 되게 작성해놓았습니다

2023-05-20 03:19 UTC, Tmdhoon2 commented on presentation/src/main/java/team/aliens/dms_android/feature/notice/NoticesViewModel.kt
> +}*/
이 pr에서 예외처리 부분을 같이 구현해야 해서 아직 작업 덜 끝났다고 이해해주시면 될 것 같아요

2023-05-20 11:25 UTC, chlgkdms commented on presentation/src/main/java/team/aliens/dms_android/feature/notice/NoticesViewModel.kt
> +}*/
아 넵 확인했습니당

2023-05-23 12:58 UTC, chlgkdms approved these changes

2023-05-28 10:46 UTC, JunJaBoy requested changes

2023-05-28 10:46 UTC, JunJaBoy commented on design-system/src/main/java/team/aliens/design_system/component/notice.kt
> +            if (index == 0) this@LazyColumn.Space(space = 16.dp)
LazyColumn의 spacedBy() 사용하시고, LazyColumn 자체 modifier에 패딩 주면 Space와 동일하게 구현할 수 있을 것 같아요.
https://developer.android.com/jetpack/compose/lists?hl=ko#content-spacing

2023-05-28 10:46 UTC, JunJaBoy commented on design-system/src/main/java/team/aliens/design_system/component/notice.kt
디자인시스템은 건들 수 없는 영역인가봅니다..

2023-05-28 10:46 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/cafeteria/CafeteriaScreen.kt
여기 코드 컨플릭트 날 것 같네요.. 제 코드가 한참 뒤에 작성되긴 했지만, 새 코드 먼저 머지하고 나서 이 브랜치 파일 체인지 discard해도 될 것 같아요.

2023-05-28 10:46 UTC, JunJaBoy commented
여기 다시 작업 부탁드릴게요

2023-05-29 14:27 UTC, chlgkdms reviewed
여기 컨플릭트 나는데 고쳐야할 것 같아요

2023-06-01 02:01 UTC, JunJaBoy requested changes

2023-06-01 02:01 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/notice/NoticesViewModel.kt
Notices랑 NoticeDetails랑 같은 뷰모델을 쓰기에는, 서로 안 쓰이는 함수와 State 프로퍼티가 너무 많아요

2023-06-01 02:01 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/notice/NoticesViewModel.kt
> +        fetchNoticeDetails()
notice id는 `fetchNoticeDetails()`의 `onSuccess` 블럭에서도 설정해주는 것 같네요

2023-06-01 02:04 UTC, JunJaBoy requested changes
확인 부탁드립니다

2023-06-01 03:58 UTC, Tmdhoon2 commented on presentation/src/main/java/team/aliens/dms_android/feature/notice/NoticeState.kt
> +    val notices: List<FetchNoticesOutput.NoticeInformation>,
좋습니당

2023-06-03 14:12 UTC, chlgkdms requested changes

2023-06-03 14:12 UTC, chlgkdms commented on presentation/src/main/java/team/aliens/dms_android/feature/cafeteria/CafeteriaScreen.kt
>  import java.time.DayOfWeek.*
이거 와일드 카드 지워야할듯?

2023-06-03 14:16 UTC, closed without merging