🔀 :: 418 sign in 리팩토링
team-aliens/DMS-Android pull request #421
Opened 2023-05-26 10:50 UTC by JunJaBoy

## 개요
> sign in 로직을 리팩토링

## 작업사항
- sign in 로직 리팩토링
- 레거시 코드 제거

## 추가 로 할 말

2023-05-27 00:48 UTC, Tmdhoon2 requested changes

2023-05-27 00:48 UTC, Tmdhoon2 commented on domain/src/main/java/team/aliens/domain/model/student/Feature.kt
> +        fun trueInitialized() = Feature(
true로 초기화 시킬 일이 있을까요??..

2023-05-27 00:48 UTC, Tmdhoon2 commented on presentation/src/main/java/team/aliens/dms_android/feature/auth/signin/SignInViewModel.kt
> +            SignInUiEvent.SignIn -> this.signInWithUpdatingState()
개행해주시면 좋을 듯 하네요

2023-05-27 00:48 UTC, Tmdhoon2 commented on presentation/src/main/java/team/aliens/dms_android/feature/auth/signin/SignInViewModel.kt
> +        setState(
전체 코드에서 this. 를 쓸지 말지 통일해주시면 좋을 것 같아요

2023-05-27 00:48 UTC, Tmdhoon2 commented on presentation/src/main/java/team/aliens/dms_android/feature/auth/signin/SignInViewModel.kt
> +    private fun updateId(
updateState / setState 네이밍 다시 생각해보는게 좋을 것 같아요
내부에서는 setState 를 호출하는데 함수 네이밍은 update~~ 로 되어 있어서 내부 override 된 updateState 랑 혼동될 수 있을 것 같아요

2023-05-27 00:48 UTC, Tmdhoon2 commented on presentation/src/main/java/team/aliens/dms_android/feature/auth/signin/SignInViewModel.kt
> +    private suspend fun signIn(): Result<AuthenticationOutput> {
이건 그냥 기존 방식대로 함수 하나에서 runCatching 호출해서 .onSuccess 랑 .onFailure 로 처리하는게 가독성 측면에서 좋을 것 같아요

2023-05-27 00:48 UTC, Tmdhoon2 commented on presentation/src/main/java/team/aliens/dms_android/feature/auth/signin/SignInViewModel.kt
그리고 지금 예외 처리가 안되어 있는 것 같아요

2023-05-27 01:18 UTC, JunJaBoy commented on domain/src/main/java/team/aliens/domain/model/student/Feature.kt
> +        fun trueInitialized() = Feature(
일단 넣어두긴 했어요. initialized() 함수 이름에서부터 내부 값들을 알 수 있게 하면 좋을 것 같았습니다.

2023-05-27 01:21 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/auth/signin/SignInViewModel.kt
> +            SignInUiEvent.SignIn -> this.signInWithUpdatingState()
어느 부분을 개행하라는 말씀이신가요??

2023-05-27 01:23 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/auth/signin/SignInViewModel.kt
> +        setState(
그러게요 조금 애매하네요.. 부모 함수는 this를 명시하지 않았고, 래당 클래스의 함수는 this를 명시하였습니다.

2023-05-27 01:24 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/auth/signin/SignInViewModel.kt
> +    private fun updateId(
네 이건 set이 나을 것 같네요

2023-05-27 01:24 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/auth/signin/SignInViewModel.kt
맞아요

2023-05-28 06:19 UTC, Tmdhoon2 requested changes

2023-05-28 06:19 UTC, Tmdhoon2 commented on presentation/src/main/java/team/aliens/dms_android/feature/auth/signin/SignInViewModel.kt
> +@Stable
여기선 @Stable 이 딱히 의미가 없지 않나요??

2023-05-29 02:37 UTC, Tmdhoon2 requested changes

2023-05-29 02:37 UTC, Tmdhoon2 commented on presentation/src/main/java/team/aliens/dms_android/feature/auth/signin/SignInViewModel.kt
<img width="30%" alt="스크린샷 2023-05-29 오전 11 30 21" src="https://github.com/team-aliens/DMS-Android/assets/102812085/d3240a64-980d-43c3-baa2-162476dcd041">
<img width="30%" alt="스크린샷 2023-05-29 오전 11 31 30" src="https://github.com/team-aliens/DMS-Android/assets/102812085/f7555cb5-7dee-41aa-ab7d-c3a1be9e0267">


에러 처리가 덜 되어 있는 것 같아요..
아마 지금 브랜치에서는 새로 만든 토스트 사용하실 수 있을텐데, 기존 토스트 말고 새로운 토스트 사용해주시고,
아이디 틀린 경우에는 텍스트 필드 메시지 + 토스트 메시지가 같이 뜨고
비밀번호 틀린 경우에는 토스트로만 띄워주고 있네요
그리고 기존엔 에러 발생한 경우 중복 요청 보낼 수 없게 버튼 비활성화 되는 로직이 있었던 것 같은데 다시 확인해주실 수 있나용??
에러 발생 시 텍스트 필드에서 텍스트 변화 일어나면 에러가 사라졌던것 같은데 이 로직도 구현이 안되어 있는 것 같네요

2023-05-29 14:26 UTC, chlgkdms approved these changes

2023-05-30 04:23 UTC, Tmdhoon2 approved these changes

2023-05-30 07:13 UTC, merged