🔀 :: (#420) 잔류 신청 리팩토링
team-aliens/DMS-Android pull request #422
Opened 2023-05-27 04:24 UTC by Tmdhoon2

## 개요
> 잔류 신청 스크린을 리팩토링 했습니다.

## 작업사항
- 잔류 신청 뷰모델 리팩토링
- 잔류 신청 스크린 컴포저블 함수 리팩토링
- 사용자 UI 개선 (padding, 정렬 등)

## 추가 로 할 말

2023-05-27 11:39 UTC, JunJaBoy requested changes

2023-05-27 11:39 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/remain/RemainApplicationEvent.kt
> +sealed class RemainsApplicationEvent : UiEvent {
~UiEvent로 명명해주세요

2023-05-27 11:39 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/remain/RemainApplicationState.kt
> +data class RemainsApplicationState(
~UiState로 명명해주세요

2023-05-27 11:39 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/remain/RemainApplicationState.kt
> +                endTime = "",
start, end는 null로 해두시면 좋을 것 같아요. 스크린에 기본값을 표시하는 대신 스켈레톤 효과를 넣으면 좋을 것 같네요.

2023-05-27 11:39 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/remain/RemainApplicationViewModel.kt
> +    // TODO BaseViewModel (MviViewModel) 에서 처리할 수 있는 방법 생각해보기
함수 원형을 MviViewModel에 넣는 건 괜찮을 것 같네요. 이전 ViewModel처럼, 처리할 예외를 MviViewModel이 알고 있으면 스크린별로 유연하게 예외 처리가 곤란하다고 해야 할까요

2023-05-27 11:39 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/remain/RemainApplicationViewModel.kt
> +                        remainsOptionId = uiState.value.remainsOptionId!!,
!! 대신 널체크 로직이 있으면 좋을 것 같아요

2023-05-27 11:39 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/remain/RemainApplicationViewModel.kt
> +                    application.getString(R.string.error_internal_server)
코드가 중복되네요

2023-05-27 11:39 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/remain/RemainsApplicationScreen.kt
selectedItemId 이런건 screen에서 관리해주면 안될 것 같네요. 파일 변경이 너무 커서 렌더링이 안되는데, 몇 가지 적어볼테니 다시 확인해주세요.

2023-05-27 11:39 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/remain/RemainsApplicationScreen.kt
rememberAppState() 사용하면 매 호출마다 각기 다른 appState가 생성되는거 아닌가요?

2023-05-27 11:39 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/remain/RemainsApplicationScreen.kt
`state` 변수에 collectAsState().value로 하면 화면 업데이트가 제대로 이루어지나요? collectAsState()까지만 해야지 State가 반환되고, 그 State의 변경에 따라 리컴포지션이 일어나는걸로 알고 있긴 한데, .value로 값을 참조할 때 리컴포지션이 잘 일어나지 않는 경험이 있어서 여쭤봅니다.

2023-05-27 11:39 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/remain/RemainsApplicationScreen.kt
`buttonEnabled` true false 여부도 VM에서 관리해줘야 할 것 같네요

2023-05-27 11:39 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/remain/RemainsApplicationScreen.kt
90번 라인부터 시작하는 코드.. 스크린 생성 후 초기 호출되어야 하는 코드같은데, 만약 맞다면 viewmodel의 init 블럭 사용해주세요.

2023-05-27 11:39 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/remain/RemainsApplicationScreen.kt
그리고 100번째 줄부터 있는 코드들은 바로 위 커멘트 참고하셔서 코드 작성하시면, collect를 LaunchedEffect 블럭 밖에서, 그리고 여기서 총 두 번 해주는 상황이 없어질 것 같네요

2023-05-27 11:39 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/remain/RemainApplicationState.kt
state, event는 viewmodel이랑 한 파일 내로 두는게 관리하기 좋을 것 같다고 생각해요. 승훈님은 어떻게 생각하시나요?

2023-05-27 11:39 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/remain/RemainsApplicationScreen.kt
158번째 줄부터 있는 itemsIndexed 함수에서, index 정보를 사용하지 않는 것 같은데 그냥 items를 쓸 수는 없는지 확인해주실 수 있나요? 그리고 내부에 selected 상태 구분하는 코드 다시 생각해주실 수 있을까요..

2023-05-27 11:39 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/remain/RemainsApplicationScreen.kt
컴포저블 맨 마지막 잔류 신청 버튼의 onEvent 함수도 Screen 컴포저블 내에 변수로 선언해주시면 관리 편할 것 같아요

2023-05-27 11:39 UTC, JunJaBoy commented on presentation/src/main/res/values/strings.xml
`remains`로 수정 부탁드릴게요

2023-05-28 00:35 UTC, Tmdhoon2 commented on presentation/src/main/java/team/aliens/dms_android/feature/remain/RemainApplicationViewModel.kt
> +    // TODO BaseViewModel (MviViewModel) 에서 처리할 수 있는 방법 생각해보기
아 사실 예외 메세지가 뷰모델마다 다 같은게 아니기도 하고.. abstract 함수 정도로 해서 구현을 강제 시키는건 어떨까요..??

2023-05-28 02:48 UTC, Tmdhoon2 commented on presentation/src/main/java/team/aliens/dms_android/feature/remain/RemainApplicationState.kt
view model 패키지 내부에 UiEvent, UiState 라는 네이밍의 파일이 있는게 좀 그렇긴 하네요..
앞으로 리팩토링 하면서 하나씩 개선해 나가는 게 좋을 것 같아요

2023-05-28 02:50 UTC, Tmdhoon2 commented on presentation/src/main/java/team/aliens/dms_android/feature/remain/RemainApplicationState.kt
state, event 는 각 view model 종속적인 애들 같아서 준수님 말씀대로 관리해도 괜찮을 것 같네요.

2023-05-28 10:36 UTC, JunJaBoy requested changes

2023-05-28 10:36 UTC, JunJaBoy commented on domain/src/main/java/team/aliens/domain/model/remains/FetchRemainsApplicationTimeOutput.kt
이 프로퍼티들이 널인 경우가 있나요

2023-05-28 10:36 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/navigator/HomeNavigation.kt
> +internal fun NavGraphBuilder.homeNavigation(
# 완전 최고에요
![image](https://github.com/team-aliens/DMS-Android/assets/101160207/ea2315e7-29c4-4c80-a4f4-36fa73cd2ebf)

2023-05-28 10:36 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/remain/RemainApplicationViewModel.kt
> +    // TODO BaseViewModel (MviViewModel) 에서 처리할 수 있는 방법 생각해보기
음.. 그렇게되면 예외 처리가 필요 없는 스크린에서까지 예외 처리가 강제되기 때문에 문제입니다. abstract 말고 일반 함수를 상위 클래스에 선언하고, 내부 구현은 진짜 공백으로 두면, 예외 처리 함수 구현이 필요한 클래스별로 오버라이드해서 사용할 수 있을 것 같네요.

2023-05-28 10:36 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/remain/RemainApplicationViewModel.kt
> +    // TODO BaseViewModel (MviViewModel) 에서 처리할 수 있는 방법 생각해보기
그런데 개인적으로 예외 처리를 추상 뷰모델에서 처리하는 건 정말 좋은데, 에러 또한 textfield의 에러 메시지, 토스트 메시지 등 state를 변경하는건데 꼭 함수를 새로 만들 필요가 있을까요?

2023-05-28 10:36 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/remain/RemainApplicationViewModel.kt
> +                    else -> R.string.error_internal_server
이 리소스는 `InternalServerError` 클래스에 대한 반환값으로 주시고, else 구문에는 `Unknown` 예외를 넣으면 좋을 것 같네요

2023-05-28 10:36 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/remain/RemainApplicationViewModel.kt
> +    val selectedRemainsOption: Pair<String, UUID?>,
제가 이해하기론 first String이 잔류 항목 이름, second UUID가 잔류 항목 아이디인데, 잔류 항목의 null 가능성때문에 잔류 항목 이름의 안정성을 포기할 수도 있을 것 같네요.. 사실 잔류 항목 이름이 서버로부터 내려왔으면 UUID 또한 null일 수 없을 것 같다고 생각됩니다. 뭐 이건 다른 얘기고, 선택된 잔류 항목 이름과 아이디는 따로 분리하는게 좋을 것 같네요.

2023-05-28 10:36 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/remain/RemainApplicationViewModel.kt
> +    val remainsOptionsOutput: FetchRemainsOptionsOutput,
Output을 쓰고 있지만, 엔티티를 새로 구현하는게 좋을 것 같아요. Screen 입장에서 ~output라는 이름의 데이터는, Screen의 어느 부분에 적합한 데이터인지 분간이 애매하겠네요..

2023-05-28 10:36 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/remain/RemainApplicationViewModel.kt
> +                endTime = null,
아마 이걸 위해서 RemainsApplicationTimeOutput을 null로 두신 것 같은데, 그냥 State의 `FetchRemainsApplicationTimeOutput` 프로퍼티 자체를 optional로 지정하면 되는거 아닌가요?

2023-05-28 10:36 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/remain/RemainApplicationViewModel.kt
> +            remainsOptionsOutput = FetchRemainsOptionsOutput(
요것도 `RemainsOption`이라는, 잔류 항목 이름과 아이디를 가지고 있는 클래스 하나 만들고, 그 클래스의 리스트(`List<RemainsOption>`) 타입을 가지는 프로퍼티로 바꿀 수 있을 것 같아요.

2023-05-28 10:36 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/remain/RemainApplicationViewModel.kt
> +data class RemainsApplicationUiState(
```suggestion
internal data class RemainsApplicationUiState(
```

2023-05-28 10:36 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/remain/RemainApplicationViewModel.kt
> +sealed class RemainsApplicationUiEvent : UiEvent {
```suggestion
internal sealed class RemainsApplicationUiEvent : UiEvent {
```

2023-05-28 10:36 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/remain/RemainApplicationViewModel.kt
> +    ) : RemainsApplicationUiEvent()
이렇게 값을 주는 것도 괜찮을 것 같네요. 개인적인 의견이지만, 어차피 RemainsOption의 리스트를 가지니까, 해당 값의 인덱스를 전달해주면 안될까요? 그럼 ViewModel에서
```kotlin
val remainsOption = uiState.remainsOptions[index]
val title = remainsOption.title
val optionId = remainsOption.id
```
이런 식으로 참조할 수 있을 것 같네요.

2023-05-28 10:36 UTC, JunJaBoy commented on presentation/src/main/res/values/strings.xml
> +    <string name="remains_remains_description">주말 기숙사 잔류 여부를 확인하고, 잔류 신청을 통해서 잔류 또는 귀가를 신청해 보세요</string>
remains_description으로 하면 어떨까요?

2023-05-28 10:36 UTC, JunJaBoy commented on presentation/src/main/res/values/strings.xml
> +    <string name="remains_time_application_available">잔류 신청 시간은 %s 까지 입니다.</string>
`remains_available_remains_application_time_is`

2023-05-28 10:39 UTC, JunJaBoy requested changes

2023-05-28 10:39 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/remain/RemainsApplicationScreen.kt
# 2

2023-05-28 10:39 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/remain/RemainsApplicationScreen.kt
60번째 줄에 private 접근제한자 붙여도 될 것 같아요

2023-05-28 10:39 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/remain/RemainsApplicationScreen.kt
@Tmdhoon2 혹시 파일 수정 하셨나요?

2023-05-28 14:24 UTC, Tmdhoon2 commented on presentation/src/main/java/team/aliens/dms_android/feature/remain/RemainApplicationViewModel.kt
> +    // TODO BaseViewModel (MviViewModel) 에서 처리할 수 있는 방법 생각해보기
> 음.. 그렇게되면 예외 처리가 필요 없는 스크린에서까지 예외 처리가 강제되기 때문에 문제입니다. abstract 말고 일반 함수를 상위 클래스에 선언하고, 내부 구현은 진짜 공백으로 두면, 예외 처리 함수 구현이 필요한 클래스별로 오버라이드해서 사용할 수 있을 것 같네요.

이 방법은 좋은 것 같은데 텍스트 필드 에러 메시지 같은 경우는 상황마다 에러가 제한적이니까 (예를 들면 로그인 아이디 같은 경우 NotFound 등) 따로 setIdTextFieldErrorMessage() 이런식으로 함수로 만들어도 될 것 같아요

2023-05-28 14:25 UTC, Tmdhoon2 commented on presentation/src/main/java/team/aliens/dms_android/feature/remain/RemainsApplicationScreen.kt
@JunJaBoy 수정완료했습니다!

2023-05-28 14:26 UTC, Tmdhoon2 commented on presentation/src/main/java/team/aliens/dms_android/feature/navigator/HomeNavigation.kt
> +internal fun NavGraphBuilder.homeNavigation(
![image](https://github.com/team-aliens/DMS-Android/assets/102812085/9fa89f09-6bdf-4428-8728-f6e9b21afa40)

2023-05-29 01:19 UTC, JunJaBoy commented
@Tmdhoon2  코드 업데이트가 안되어있어요

2023-05-29 04:16 UTC, JunJaBoy requested changes

2023-05-29 04:16 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/remain/RemainApplicationViewModel.kt
> +    // TODO BaseViewModel (MviViewModel) 에서 처리할 수 있는 방법 생각해보기
넵 그런건 저도 많이많이 사용하고 있습니다! 함수가 하는 일을 최소한으로 제한하니 좋습니다.

2023-05-29 05:24 UTC, Tmdhoon2 commented on di/src/main/java/team/aliens/di/remote/HttpModule.kt
> +            baseUrl = "https://api-dev.aliens-dms.com",
실수 ㅎㅎ...

2023-05-29 14:29 UTC, chlgkdms approved these changes

2023-05-30 04:25 UTC, Tmdhoon2 commented on presentation/src/main/java/team/aliens/dms_android/feature/remain/RemainApplicationViewModel.kt
> +    private val application: Application = Application(),
스크린에서 예외 처리 하는 방식으로 변경할게용

2023-06-03 06:25 UTC, chlgkdms requested changes

2023-06-03 06:25 UTC, chlgkdms commented on remote/src/main/java/team/aliens/remote/model/remains/FetchCurrentAppliedRemainsOptionResponse.kt
> +    @SerializedName("id") val appliedRemainsOptionId: UUID, // todo
이건 무슨 todo인가요?

2023-06-03 06:25 UTC, chlgkdms commented on presentation/src/main/java/team/aliens/dms_android/feature/remain/RemainsApplicationScreen.kt
> +                        uiState.selectedRemainsOption?.title ?: "코딱지",
??

2023-06-03 07:08 UTC, Tmdhoon2 commented on presentation/src/main/java/team/aliens/dms_android/feature/remain/RemainApplicationViewModel.kt
> +                setState(
음 현재 신청된 잔류 항목 불러오기를 여기서 다시 호출해줘야 하지 않을까요??
이렇게 되면 신청 하고 나서 화면 나갔다 들어와야 신청 완료가 반영이 될 것 같아요

2023-06-03 10:19 UTC, chlgkdms approved these changes

2023-06-03 12:01 UTC, merged