🔀 :: (#426) 상벌점 내역 확인 스크린 리팩토링
team-aliens/DMS-Android pull request #428
Opened 2023-05-29 08:10 UTC by JunJaBoy

## 개요
> 상벌점 내역 확인 스크린을 리팩토링합니다.

## 작업사항
- 상벌점 내역 확인 패키지 이동
- 레거시 코드 제거
- 코드 리팩토링

## 추가 로 할 말

2023-05-29 12:26 UTC, Tmdhoon2 requested changes

2023-05-29 12:26 UTC, Tmdhoon2 commented on presentation/src/main/java/team/aliens/dms_android/feature/mypage/pointhistory/PointHistoryScreen.kt
> +        Spacer(Modifier.height(36.dp))
디자인 시스템 Space 사용 부탁드립니당

2023-05-29 12:26 UTC, Tmdhoon2 commented on presentation/src/main/java/team/aliens/dms_android/feature/mypage/pointhistory/PointHistoryScreen.kt
> +                item {
여기 LazyColumn 내부 modifier 로 padding 줄 수 있는지 한 번만 확인해주세용

2023-05-29 14:32 UTC, chlgkdms approved these changes

2023-05-30 07:56 UTC, Tmdhoon2 requested changes

2023-05-30 07:56 UTC, Tmdhoon2 commented on presentation/src/main/java/team/aliens/dms_android/feature/mypage/pointhistory/PointHistoryScreen.kt
> +                        text = "짠! 야옹맨이 너의 점수를 가져갔으니 안심하라구!",
아 맞다 이거 머지할 때는 주석처리라던가 조치를 취해주세요

2023-05-30 10:37 UTC, Tmdhoon2 approved these changes

2023-05-30 10:37 UTC, Tmdhoon2 approved these changes

2023-05-30 10:41 UTC, merged