🔀 :: (#427) authorizationinterceptor 수정
team-aliens/DMS-Android pull request #432
Opened 2023-05-31 22:47 UTC by JunJaBoy

## 개요
> AuthorizationInterceptor를 수정합니다

## 작업사항
- AuthorizationFacade 수정
- AuthorizationInterceptor 수정
- TokenReissueManager/impl 구현
- Thread defaultExceptionHandler 설정

## 추가 로 할 말

2023-05-31 23:23 UTC, chlgkdms commented on design-system/src/main/java/team/aliens/design_system/toast/toast.kt
> +                    //throw IllegalArgumentException()
이 주석은 왜 해준건가요?

2023-05-31 23:33 UTC, JunJaBoy commented on design-system/src/main/java/team/aliens/design_system/toast/toast.kt
> +                    //throw IllegalArgumentException()
토스트 코드에서 npe가 발생했었는데, 이 코드가 원인이었습니다. 주석 처리 후 커밋했고, 코드 작성자에게도 말씀드렸습니다.

2023-06-01 01:28 UTC, chlgkdms approved these changes

2023-06-01 01:36 UTC, limsaehyun commented on design-system/src/main/java/team/aliens/design_system/toast/toast.kt
> +                    //throw IllegalArgumentException()
이 부분에 들어가야할 코드는 무엇인가요?
추후 작업 예정이라면 TODO 처리 해주세요

2023-06-01 01:36 UTC, limsaehyun commented on presentation/src/main/java/team/aliens/dms_android/handler/DmsExceptionHandler.kt
> +        Log.w(
디버그용 로그라면
디버그 모드에서만 실행될 수 있도록 설정해주세요.

2023-06-01 01:50 UTC, Tmdhoon2 requested changes

2023-06-01 01:50 UTC, Tmdhoon2 commented on presentation/src/main/java/team/aliens/dms_android/handler/DmsExceptionHandler.kt
>      override fun uncaughtException(
이 함수는 단순히 로그 찍는 역할만 하는건가요??

2023-06-01 01:50 UTC, Tmdhoon2 commented on remote/src/main/java/team/aliens/remote/http/AuthorizationInterceptor.kt
> +    private fun okhttp3.Request.shouldBeIgnored(): Boolean {
import okhttp3.Request 선언해서 사용 부탁드릴게용

2023-06-01 01:50 UTC, Tmdhoon2 commented on presentation/src/main/java/team/aliens/dms_android/handler/DmsExceptionHandler.kt
DmsExceptionHandler 가 기존의 HttpRequestHandler 를 대체하게 되는건가요...??

2023-06-01 02:11 UTC, JunJaBoy commented on data/src/main/java/team/aliens/data/facade/AuthorizationFacade.kt
>  class AuthorizationFacade @Inject constructor(
DI 때문에 public으로 선언해두었습니다

2023-06-01 02:11 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/handler/DmsExceptionHandler.kt
아니요 `DmsExceptionHandler`는 앱의 전역적인 Runtime Exception을 핸들링하는 용도고, HttpRequestHandler가 `sendHttpRequest()`를 말씀하시는게 맞다면, `HttpRequestHandler`는 Http 요청을 보내고 응답의 상태 코드에 대한 작업을 핸들링하는 겁니다.

2023-06-01 02:11 UTC, JunJaBoy commented on remote/src/main/java/team/aliens/remote/http/AuthorizationInterceptor.kt
> +    private fun okhttp3.Request.shouldBeIgnored(): Boolean {
바로 아래 코드의 `Request`가 우리 프로젝트에서 정의된 Request입니다. OkHttp의 Request와 네이밍이 겹쳐서 okHttp의 Request 네임스페이스를 따로 명시해 두었어요(안 하면 컴파일 에러 발생합니다)..

2023-06-01 02:13 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/handler/DmsExceptionHandler.kt
> +        Log.w(
디버그용 로거를 주입하는 모듈을 작성할 생각이었는데, PR 범위가 커질 것 같아서 저렇게 작성해 두었습니다. 앱에서 발생하는 예외는 모두 이 코드로 로깅을 하고, 프로세스를 종료하도록 작성해 두었습니다. 혹시 로그를 빼는게 나을까요?

2023-06-01 02:14 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/handler/DmsExceptionHandler.kt
>      override fun uncaughtException(
당장은 그런 용도이긴 합니다. 나중에 navigateToSignIn 등의 로직을 구현할 수도 있을 것 같아요. 네트워크 connection이 끊기는 상황이 생겨도 여기에서 처리해줄 수 있고요.

2023-06-01 03:04 UTC, aahspringaa4 approved these changes

2023-06-01 03:35 UTC, Tmdhoon2 approved these changes

2023-06-01 04:03 UTC, merged