🔀 :: (#413) 공지사항 로직 리팩토링
team-aliens/DMS-Android pull request #435
Opened 2023-06-01 10:50 UTC by Tmdhoon2

## 개요
> 공지사항 로직을 리팩토링 했습니다

## 작업사항
- 전 pr 에서 작업했던 코드들을 걷어내고 다시 리팩토링 했습니다
- 예외 처리는 잠시 미뤄두었습니다
- 디자인 시스템 notice 컴포넌트들을 notice screen 으로 옮겼습니다

## 추가 로 할 말

2023-06-01 13:50 UTC, JunJaBoy requested changes

2023-06-01 13:50 UTC, JunJaBoy commented on local/src/main/java/team/aliens/local/room/entity/NoticeEntity.kt
나중에 다시 고민해봐야 할 것 같네요..

2023-06-01 13:50 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/notice/NoticeScreen.kt
> +                else R.string.latest_order
stringResource 사용할 수 있을 것 같습니다

2023-06-01 13:50 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/notice/NoticeScreen.kt
> +    onClick: (UUID) -> Unit,
onNoticeClick으로 바꿔주세요

2023-06-01 13:50 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/notice/NoticesViewModel.kt
> +) : MviViewModel<NoticesUiState, NoticesUiEvent>(NoticesUiState.initial()) {
```suggestion
) : MviViewModel<NoticesUiState, NoticesUiEvent>(
    initialState = NoticesUiState.initial(),
) {
```

2023-06-01 13:50 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/notice/NoticesViewModel.kt
> +                    notices = it.notices.toModel()
```suggestion
                    notices = it.notices.toModel(),
```

2023-06-01 13:50 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/notice/NoticesViewModel.kt
> +                    notices = it.notices.toModel()
요건 줄바꿈 안 하면 코드 정리할 때 한 줄로 대체될 듯..

2023-06-01 13:50 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/notice/NoticesViewModel.kt
> +            }
```suggestion
            }
```

2023-06-01 13:50 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/notice/NoticesViewModel.kt
> +            }
사용되지 않는 코드 블럭같아요

2023-06-01 13:50 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/notice/NoticesViewModel.kt
> +            }
```suggestion
            }
```
여기도요

2023-06-01 13:50 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/notice/NoticesViewModel.kt
> +    ) {
```suggestion
    private fun setNotices(
        notices: List<Notice>,
    ) {
```

```suggestion
    private fun setNotices(notices: List<Notice>) {
```

2023-06-01 13:50 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/notice/NoticesViewModel.kt
> +                }
뭐 크게 상관 없다고 생각되지만, 케이스가 OLD, NEW 두 개만 있어서 `if-else`로 구현할 수 있을 것 같네요
```suggestion
                order = {
                    val currentOrder = uiState.value.order
                    if (currentOrder == Order.NEW) Order.OLD else Order.NEW
                }
```

2023-06-01 13:50 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/notice/NoticesViewModel.kt
> +    class FetchNoticeDetails(val noticeId: UUID): NoticesUiEvent()
요건 제가 넘겨받아서 다시 구성해보도록 하겠습니다..

2023-06-01 22:43 UTC, Tmdhoon2 commented on presentation/src/main/java/team/aliens/dms_android/feature/notice/NoticeScreen.kt
> +                else R.string.latest_order
button onClick 함수가 일반 함수라서 사용이 불가능하지 않나요??...

2023-06-02 03:23 UTC, JunJaBoy requested changes

2023-06-02 03:23 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/notice/NoticesViewModel.kt
> +                fetchNotices()
`fetchNotices()` 함수에 order를 파라미터로 넣어주는 코드는 어떨까요? 그냥 질문 ..

2023-06-02 03:23 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/notice/NoticesViewModel.kt
> +                fetchNotices()
그리고 그 order로 fetchNotices가 성공하면 setState하면서 order와 notices를 한 번에 state에 지정하는거죠

2023-06-02 03:23 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/notice/NoticesViewModel.kt
> +                else Order.NEW,
```kotlin
                order = if (uiState.value.order == Order.NEW) Order.OLD
                else if (uiState.value.order == Order.OLD) Order.NEW
                else throw IllegalStateException(),
```

요렇게 if문이나 when문 사용하는게 더 안전한 코드같습니다!

2023-06-02 06:10 UTC, Tmdhoon2 commented on presentation/src/main/java/team/aliens/dms_android/feature/notice/NoticeScreen.kt
>      val isNoticeServiceEnabled = LocalAvailableFeatures.current[Extra.isNoticeServiceEnabled]
아직 쓰이진 않아요 나중에 공지사항 비활성화가 요구사항에 추가되면 그때 쓰일 것 같아요!

2023-06-02 06:12 UTC, Tmdhoon2 commented on presentation/src/main/java/team/aliens/dms_android/feature/notice/NoticesViewModel.kt
> +                fetchNotices()
오 좋은데요?

2023-06-02 06:17 UTC, Tmdhoon2 commented on presentation/src/main/java/team/aliens/dms_android/feature/notice/NoticeScreen.kt
> +        verticalArrangement = Arrangement.spacedBy(12.dp),
이게 그 lazy column 전체 패딩이 아니라 item 간 padding 이라서 Arrangement 로 주는게 맞을 것 같아요!!

2023-06-02 06:23 UTC, Tmdhoon2 commented on presentation/src/main/java/team/aliens/dms_android/feature/notice/NoticesViewModel.kt
> +                fetchNotices()
사실 그렇게 구현하면 uiState 에 있는 order 가 쓰일 일이 없어질 것 같아요!
밑에 코멘트 주신 IllegalException 도 setOrder 에서 처리해주고 있기도 하고, 차라리 두 함수를 하나로 합치고, 적절한 네이밍을 붙이는 것과 같은 방법들이 더 좋을 수도 있을 것 같아요!!

2023-06-02 06:34 UTC, Tmdhoon2 commented on presentation/src/main/java/team/aliens/dms_android/feature/notice/NoticeScreen.kt
> +            navController.navigate("noticeDetails/${noticeId}")
설명 한 번만 더 해주실 수 있나용..??

2023-06-02 06:53 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/notice/NoticeScreen.kt
> +            navController.navigate("noticeDetails/${noticeId}")
이 함수 자체를 상위 컴포저블에 정의해주세요

2023-06-02 06:53 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/notice/NoticeScreen.kt
>      val isNoticeServiceEnabled = LocalAvailableFeatures.current[Extra.isNoticeServiceEnabled]
넴 그럼 일단 지워주세요!

2023-06-02 08:44 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/notice/NoticeScreen.kt
> +        verticalArrangement = Arrangement.spacedBy(12.dp),
아 그게 아니라 위에 modifier padding이요

2023-06-02 08:45 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/notice/NoticesViewModel.kt
> +                fetchNotices()
사용저 화면에 현재 선택된 정렬 순서 보여줄 때 활용할 수 있겠네요

2023-06-02 08:46 UTC, JunJaBoy requested changes
.

2023-06-02 08:48 UTC, JunJaBoy requested changes
커멘트 확인해 주시고, 커밋 메시지에 리뷰 반영보다 리뷰에 의해서 어떤 작업을 했는지 알려주심 좋을 것 같아요!

2023-06-02 10:29 UTC, chlgkdms approved these changes

2023-06-03 13:28 UTC, Tmdhoon2 commented on presentation/src/main/java/team/aliens/dms_android/feature/Home.kt
> +    }
이 함수를 혹시 상위 컴포저블 함수로 빼신 이유가 있나요

2023-06-03 13:31 UTC, chlgkdms approved these changes

2023-06-03 13:40 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/notice/NoticesViewModel.kt
> +        fetchNotices(Order.NEW)
음.. 원래 승훈님이 말씀하신대로 코드를 짰었는데, 뷰모델 초기 목록을 불러올 때 최신순으로 불러온다는 걸 한 눈에 파악하기 어렵더라구요

2023-06-03 13:42 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/Home.kt
> +    }
navController를 굳이 전달해 줄 필요가 없겠더라고요. 그리고 개인적으로 컴포저블 함수는 최대한 재활용될 수 있도록 만들어야(비록 스크린처럼 한 번만 사용되는 화면이더라도) 깔끔한 코드라고 생각해요.

2023-06-03 14:16 UTC, JunJaBoy approved these changes

2023-06-03 14:16 UTC, merged