🔀 :: (#439) 2차 리팩토링
team-aliens/DMS-Android pull request #443
Opened 2023-06-11 12:12 UTC by JunJaBoy

## 개요
> 2차 리팩토링한 작업 내역을 머지합니다

## 작업사항
- 신청 스크린 리팩토링
- 마이페이지 리팩토링
- 날짜 전환을 급식 카드 넘기는 방법으로 가능하게 하는 로직 구현
- 바텀내비게이션 애니메이션 구현
- 급식 스크린 애니메이션 구현

## 추가 로 할 말

2023-06-11 13:35 UTC, chlgkdms requested changes

2023-06-11 13:35 UTC, chlgkdms commented on presentation/src/main/java/team/aliens/dms_android/feature/home/Home.kt
> +import androidx.compose.material.*
와일드카드 없애주세요!

2023-06-11 13:58 UTC, Tmdhoon2 requested changes

2023-06-11 13:58 UTC, Tmdhoon2 commented on domain/src/main/java/team/aliens/domain/model/student/FetchMyPageOutput.kt
> +        schoolName = schoolName,
여기는 this 붙이는걸로 통일할까요??

2023-06-11 13:58 UTC, Tmdhoon2 commented on presentation/src/main/java/team/aliens/dms_android/feature/home/application/ApplicationScreen.kt
> +    val buttonTextRes: Int,
```suggestion
    @StringRes val titleRes: Int,
    @StringRes val descriptionRes: Int,
    @StringRes val buttonTextRes: Int,
```

2023-06-11 13:58 UTC, Tmdhoon2 commented on presentation/src/main/java/team/aliens/dms_android/feature/home/mypage/MyPageViewModel.kt
> +            }.onSuccess {
예외 처리가 따로 필요 없는 함수면 usecase 만 호출해도 되지 않을까요??...

2023-06-11 13:58 UTC, Tmdhoon2 commented on presentation/src/main/java/team/aliens/dms_android/feature/home/mypage/MyPageScreen.kt
> +    val pointServiceEnabled = LocalAvailableFeatures.current[Extra.isPointServiceEnabled] ?: false
음 Application Screen 쪽에선 상위 컴포저블 함수에서 이 값을 전달해주는 것 같던데, 여기선 LocalComposition 으로 구현이 되어 있네요 구현 방식에 차이가 있는 이유가 있을까요??

2023-06-11 13:58 UTC, Tmdhoon2 commented on presentation/src/main/java/team/aliens/dms_android/feature/home/mypage/MyPageScreen.kt
> +
제거 부탁드립니당

2023-06-12 03:12 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/home/mypage/MyPageViewModel.kt
> +            }.onSuccess {
SideEffect 발생시킬 때 잊어먹지 않으려고 남겨두긴 했는데.. 크게 상관없지 않다면 코드 수정하지 않고 둬도 괜찮을까요?

2023-06-12 03:15 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/home/mypage/MyPageScreen.kt
> +    val pointServiceEnabled = LocalAvailableFeatures.current[Extra.isPointServiceEnabled] ?: false
이유는 크게 없구요,, ApplicationScreen쪽에서 사용한 방법이 다른 코드랑 통일성 측면에서 괜찮을 것 같네요

2023-06-12 03:18 UTC, Tmdhoon2 commented on presentation/src/main/java/team/aliens/dms_android/feature/home/mypage/MyPageViewModel.kt
> +            }.onSuccess {
아! 알겠습니당!!

2023-06-12 03:19 UTC, Tmdhoon2 commented on presentation/src/main/java/team/aliens/dms_android/feature/home/mypage/MyPageScreen.kt
> +    val pointServiceEnabled = LocalAvailableFeatures.current[Extra.isPointServiceEnabled] ?: false
그러면 ApplicationScreen 쪽에서 작업한 방식대로 구현 부탁드려도 괜찮을까요??

2023-06-12 03:58 UTC, Tmdhoon2 requested changes

2023-06-12 03:58 UTC, Tmdhoon2 commented on presentation/src/main/java/team/aliens/dms_android/feature/home/Home.kt
> +                                durationMillis = 8_0
언더바가 따로 의미하는게 있나요??

2023-06-12 03:59 UTC, JunJaBoy commented on presentation/src/main/java/team/aliens/dms_android/feature/home/Home.kt
> +                                durationMillis = 8_0
enter, exit transaction 시간을 각각 일괄 변경할 때 구분하기 위해 적어뒀고, 이 문법은 코틀린에서 숫자 언더바 표현 찾아보심 될것같아요

2023-06-12 04:04 UTC, Tmdhoon2 approved these changes

2023-06-12 04:50 UTC, chlgkdms approved these changes

2023-06-12 06:08 UTC, merged