🔀 :: (#445) exception 클래스 구현
team-aliens/DMS-Android pull request #460
Opened 2023-06-16 05:28 UTC by chlgkdms

## 개요
> 각 api별 exception 클래스를 구현했습니다

## 작업사항
- exception 클래스 구현

## 추가 로 할 말

2023-06-16 10:05 UTC, JunJaBoy commented
모든 파일 마지막 줄 라인브레이크 추가해주세요

2023-06-16 10:15 UTC, chlgkdms commented
> 모든 파일 마지막 줄 라인브레이크 추가해주세요

추

2023-06-16 10:16 UTC, chlgkdms commented
> 모든 파일 마지막 줄 라인브레이크 추가해주세요

추가했습니다!

2023-06-16 10:19 UTC, JunJaBoy requested changes

2023-06-16 10:19 UTC, JunJaBoy commented on domain/src/main/java/team/aliens/domain/exception/RemainException.kt
Remains로 바꿔주세요

2023-06-16 10:19 UTC, JunJaBoy commented on domain/src/main/java/team/aliens/domain/exception/RemainException.kt
> +    object DoNotRemainApply : RemainException(
무슨 오류인가요

2023-06-16 10:19 UTC, JunJaBoy commented on domain/src/main/java/team/aliens/domain/exception/NoticeException.kt
> +    object NoticesNotFound : NoticeException(
명세서에 공지사항 목록을 찾을 수 없다는 오류는 따로 없어보이네요.

2023-06-16 10:19 UTC, JunJaBoy commented on domain/src/main/java/team/aliens/domain/exception/NoticeException.kt
> +    object NoticesNotFound : NoticeException(
아마 공지 상세 찾을 수 없음 같습니다

2023-06-16 10:19 UTC, JunJaBoy commented on domain/src/main/java/team/aliens/domain/exception/RemainException.kt
> +        message = "Not remain apply time",
```suggestion
        message = "Not remains application time",
```

2023-06-16 10:19 UTC, JunJaBoy commented on domain/src/main/java/team/aliens/domain/exception/RemainException.kt
하위 클래스, 메시지들도 동일하게 바꿔주세요

2023-06-16 10:19 UTC, JunJaBoy commented on domain/src/main/java/team/aliens/domain/exception/SchoolException.kt
> +
도메인 확인하고 다시 작성해주세요 !!

2023-06-16 10:19 UTC, JunJaBoy commented on domain/src/main/java/team/aliens/domain/exception/SchoolException.kt
> +
도메인이랑 네이밍 동일하게 가져가야 할 것 같아요

2023-06-16 10:19 UTC, JunJaBoy commented on domain/src/main/java/team/aliens/domain/exception/StudentException.kt
> +    object AuthCodeUnAuthorized : StudentException(
`Unauthorized`

2023-06-16 10:19 UTC, JunJaBoy commented on domain/src/main/java/team/aliens/domain/exception/StudentException.kt
> +        message = "Student Information mismatch",
여긴 중간에도 대문자가 있네요

2023-06-16 10:19 UTC, JunJaBoy commented on domain/src/main/java/team/aliens/domain/exception/StudentException.kt
클래스 이름 도메인이랑 동일하게 지어주세요

2023-06-16 10:19 UTC, JunJaBoy commented on domain/src/main/java/team/aliens/domain/exception/StudentException.kt
도메인 리포지토리쪽 보시면 나와있을거에요

2023-06-16 10:19 UTC, JunJaBoy commented on domain/src/main/java/team/aliens/domain/exception/StudentException.kt
> +        message = "Account Id already exists",
```suggestion
        message = "Account ID already exists",
```

2023-06-16 10:19 UTC, JunJaBoy commented on domain/src/main/java/team/aliens/domain/exception/RemainException.kt
하위 클래스명 적절한 위치에 Remains 명시해주세요

2023-06-16 10:19 UTC, JunJaBoy commented on domain/src/main/java/team/aliens/domain/exception/StudyRoomException.kt
StudyRoom 명시해주세요

2023-06-16 10:19 UTC, JunJaBoy commented on domain/src/main/java/team/aliens/domain/exception/StudyRoomException.kt
동일하게 도메인이랑 네이밍 맞춰주세요

2023-06-16 10:23 UTC, chlgkdms commented on domain/src/main/java/team/aliens/domain/exception/RemainException.kt
> +    object DoNotRemainApply : RemainException(
잔류 신청 시간 보기에 있는 잔류를 신청하지 않은 상태입니다

2023-06-16 10:26 UTC, chlgkdms commented on domain/src/main/java/team/aliens/domain/exception/NoticeException.kt
> +    object NoticesNotFound : NoticeException(
<img width="243" alt="스크린샷 2023-06-16 오후 7 25 50" src="https://github.com/team-aliens/DMS-Android/assets/88268418/9cd6c142-3031-4f82-bab0-880700b85ded">

이 부분에서 저는 상세를 찾을 수 없다기 보다는 공지사항 자체를 찾을 수 없다고 이해했습니다!

2023-06-16 10:27 UTC, Tmdhoon2 requested changes

2023-06-16 10:27 UTC, Tmdhoon2 commented on domain/src/main/java/team/aliens/domain/exception/NoticeException.kt
> +    val code: Int,
혹시 왜 여기는 프로퍼티로 선언되어 있나요??

2023-06-16 11:00 UTC, chlgkdms commented on domain/src/main/java/team/aliens/domain/exception/StudyRoomException.kt
정확히 어디에 StudyRoom을 명시하라는 말씀이신가요??

2023-06-16 11:05 UTC, chlgkdms commented on domain/src/main/java/team/aliens/domain/exception/StudentException.kt
클래스면 어디를 말하는건가요??

2023-06-16 11:06 UTC, chlgkdms commented on domain/src/main/java/team/aliens/domain/exception/NoticeException.kt
> +    val code: Int,
이미 auth랑 remote exception이 프로퍼티로 선언되어있어서 한건데.. 이유는 잘 모르겠네요

2023-06-17 02:04 UTC, JunJaBoy commented on domain/src/main/java/team/aliens/domain/exception/StudyRoomException.kt
클래스명에 StudyRoom 명시해주세요

2023-06-17 02:06 UTC, JunJaBoy commented on domain/src/main/java/team/aliens/domain/exception/RemainException.kt
> +    object DoNotRemainApply : RemainException(
.. 클래스명이 한 번에 와닿지 않네요. RemainsNotApplicated 이런 네이밍으로 다시 작성해주실 수 있나요?

2023-06-17 02:58 UTC, chlgkdms commented on domain/src/main/java/team/aliens/domain/exception/StudyRoomException.kt
> +    object NotApplicationTime : StudyRoomException(
수정했습니다

2023-06-17 02:58 UTC, chlgkdms commented on domain/src/main/java/team/aliens/domain/exception/SchoolException.kt
> +    object SchoolVerificationQuestionIsNotCertified : SchoolException(
수정했습니다

2023-06-17 03:00 UTC, chlgkdms commented on domain/src/main/java/team/aliens/domain/exception/StudentException.kt
명세서 보고 명세서에 있는 내용으로만 짜다보니 도메인이랑 안 맞았던 것 같네요..

2023-06-17 03:54 UTC, chlgkdms commented on domain/src/main/java/team/aliens/domain/exception/StudentException.kt
> +    object StudentInfoMismatch : StudentException(
수정했습니다

2023-06-17 03:57 UTC, chlgkdms commented on domain/src/main/java/team/aliens/domain/exception/StudyRoomException.kt
수정했습니다

2023-06-17 03:59 UTC, chlgkdms commented on domain/src/main/java/team/aliens/domain/exception/NoticeException.kt
> +    object NoticesNotFound : NoticeException(
수정했습니다

2023-06-17 04:03 UTC, chlgkdms commented on domain/src/main/java/team/aliens/domain/exception/RemainException.kt
> +    object DoNotRemainApply : RemainException(
수정했습니다

2023-06-17 04:05 UTC, chlgkdms commented on domain/src/main/java/team/aliens/domain/exception/RemainsException.kt
> +    )
수정했습니다

2023-06-18 09:14 UTC, JunJaBoy requested changes

2023-06-18 09:14 UTC, JunJaBoy commented on domain/src/main/java/team/aliens/domain/exception/RemainsException.kt
> +    object RemainsNotApplicated : RemainsException(
RemainsNotApplied가 좋을 것 같아요

2023-06-18 09:14 UTC, JunJaBoy commented on domain/src/main/java/team/aliens/domain/exception/RemainsException.kt
> +    object NoRemainsApplicationOption : RemainsException(
이건 명세서 어디에 있나요?

2023-06-18 10:56 UTC, chlgkdms commented on domain/src/main/java/team/aliens/domain/exception/RemainsException.kt
> +    object NoRemainsApplicationOption : RemainsException(
<img width="278" alt="스크린샷 2023-06-18 오후 7 56 24" src="https://github.com/team-aliens/DMS-Android/assets/88268418/08c85f64-2d04-4a6e-9222-decbbd1232a9">
이 부분 입니다

2023-06-18 10:58 UTC, chlgkdms commented on domain/src/main/java/team/aliens/domain/exception/RemainsException.kt
> +    object RemainsNotApplicated : RemainsException(
수정했습니다

2023-06-18 11:30 UTC, JunJaBoy approved these changes

2023-06-18 11:39 UTC, Tmdhoon2 commented on domain/src/main/java/team/aliens/domain/exception/NoticeException.kt
> +    val code: Int,
그러니까 외부에서 참조할 일이 없는 것 같던데 왜 code 만 val 로 선언되어 있냐는 질문이였어요

2023-06-18 11:59 UTC, Tmdhoon2 approved these changes

2023-06-18 12:06 UTC, merged