🔀 :: (#458) sign in 재구성
team-aliens/DMS-Android pull request #464
Opened 2023-06-20 14:30 UTC by JunJaBoy

## 개요
> sign in를 side effect 개념을 활용하여 리팩토링합니다

## 작업사항
- sign in 스크린 리팩토링

## 추가 로 할 말

2023-06-20 15:04 UTC, Tmdhoon2 requested changes

2023-06-21 00:23 UTC, aahspringaa4 approved these changes

2023-06-21 00:23 UTC, aahspringaa4 commented on domain/src/main/java/team/aliens/domain/exception/RemoteException.kt
> +    object TokenExpired : RemoteException("Token expired")
No permission 이나 Invalid token expired는 remoteException으로 분류되는 이유가 뭔가요? 클라단에서 발생한 네트워크 에러와 통신 과정에서 일어난 네트워크 에러는 따로 관리해주는게 좋아보이긴하는데

2023-06-21 03:25 UTC, Tmdhoon2 approved these changes

2023-06-21 03:28 UTC, merged