🔗 :: (#684) 안내 상세 시간 파싱
team-aliens/DMS-Android pull request #685
Opened 2024-06-04 12:20 UTC by parkuiery

## 개요
>
![image](https://github.com/team-aliens/DMS-Android/assets/128464859/c7b6ecba-4ed1-4318-9851-b1764ed32908)

## 작업사항
- 

## 추가 로 할 말

2024-06-08 03:26 UTC, JunJaBoy requested changes

2024-06-08 03:26 UTC, JunJaBoy commented on feature/src/main/java/team/aliens/dms/android/feature/notice/NoticeDetailsScreen.kt
> +
string resource 사용해서 구현해보시면 좋을 것 같아요

2024-06-08 08:52 UTC, parkuiery commented on feature/src/main/java/team/aliens/dms/android/feature/notice/NoticeDetailsScreen.kt
> +
수정했습니다

2024-06-10 01:44 UTC, JunJaBoy approved these changes

2024-06-10 06:15 UTC, merged