🔗 :: (#657) 신청화면 잔류신청하기 태그 업데이트 안됨
team-aliens/DMS-Android pull request #689
Opened 2024-06-07 06:05 UTC by parkuiery

## 개요
>신청화면 태그 업데이트 로직을 추가했습니다

## 작업사항
- 

## 추가 로 할 말

2024-06-08 03:30 UTC, JunJaBoy requested changes

2024-06-08 03:30 UTC, JunJaBoy commented on feature/src/main/java/team/aliens/dms/android/feature/main/application/ApplicationScreen.kt
> +                    if (appliedTitle != null) {
AnimatedVisibility에서 false면 밑에 if문이 의미 없는거 아닌가요?

2024-06-08 03:30 UTC, JunJaBoy commented on feature/src/main/java/team/aliens/dms/android/feature/main/application/ApplicationViewModel.kt
>      }
init 대신 oncreate를 넣으신 이유가 있나요? LIfeCycleOwner를 사용하는 것 같지 않은데..

2024-06-08 08:00 UTC, parkuiery commented on feature/src/main/java/team/aliens/dms/android/feature/main/application/ApplicationViewModel.kt
>      }
init을 사용하면 신청을 하고 뒤로돌아가기를 했을 때 태그가 업데이트가 되지 않아 생명주기를 이용하여 onCreate 될 때마다 업데이트 하도록 만들었습니다.

2024-06-08 08:04 UTC, JunJaBoy commented on feature/src/main/java/team/aliens/dms/android/feature/main/application/ApplicationScreen.kt
> +                    if (appliedTitle != null) {
코드 한 번 해석해보시죠

2024-06-10 07:02 UTC, parkuiery commented on feature/src/main/java/team/aliens/dms/android/feature/main/application/ApplicationScreen.kt
> +                    if (appliedTitle != null) {
수정했습니다

2024-06-10 11:00 UTC, JunJaBoy requested changes

2024-06-10 14:30 UTC, parkuiery commented on feature/src/main/java/team/aliens/dms/android/feature/main/application/ApplicationScreen.kt
> +                        Text(text = appliedTitle!!)
수정했습니다

2024-06-11 06:32 UTC, parkuiery commented on feature/src/main/java/team/aliens/dms/android/feature/main/application/ApplicationViewModel.kt
>      }
좋은거 같습니다.
근데 이 기능을 빨리 사용해야 해서 우선 머지하고 나중에 리펙토링 하는쪽으로 해도 될까요?

2024-06-12 00:47 UTC, JunJaBoy approved these changes

2024-06-12 00:47 UTC, JunJaBoy commented on feature/src/main/java/team/aliens/dms/android/feature/main/application/ApplicationViewModel.kt
>      }
좋습니다 😎
TODO 이슈 남겨주세요

2024-06-12 00:47 UTC, JunJaBoy commented on feature/src/main/java/team/aliens/dms/android/feature/main/application/ApplicationScreen.kt
> +                    if(appliedTitle!= null) {
흠 결국 원상복귀군요..

2024-06-12 03:01 UTC, merged