🔀 :: register package 구조 정리 및 schools 로직과 Screen연결 구현
team-aliens/DMS-Android pull request #93
Opened 2022-10-30 03:25 UTC by Leesin0222

## 개요
> 회원가입 package구조 정리 및 schools -  로직과  screen 연결

## 작업사항
- 학교 인증코드 입력과 학교 확인 질문을 구현했습니다.
- 다만 맞게 짠 코드인지 모르겠습니다. 

## 추가 로 할 말
- 전체 구현은 못했습니다.
- 많은 피드백 부탁드립니다.

2022-10-31 03:32 UTC, aahspringaa4 requested changes
뷰 작업 끝난거 사진 형태로 PR에 같이 올려주세요. 그리고 코드적으로 약간 이상한 부분이 많은데 다 컴파일 해보고 올리시는거 맞죠?

2022-10-31 03:32 UTC, aahspringaa4 commented on presentation/src/main/java/com/example/dms_android/feature/register/screen/school/ConfirmSchoolScreen.kt
> +    val notFoundComment = stringResource(id = R.string.LoginNotFound)
이건 Login예외잖아요 TooMany랑 Server Unknown은 재활용해도 400하고 404는 재활용하시면 안되죠

2022-10-31 03:32 UTC, aahspringaa4 commented on presentation/src/main/java/com/example/dms_android/feature/register/screen/school/ConfirmSchoolScreen.kt
> +    val notFoundComment = stringResource(id = R.string.LoginNotFound)
이건 Login예외잖아요 TooMany랑 Server Unknown은 재활용해도 400하고 404는 재활용하시면 안되죠

2022-10-31 03:32 UTC, aahspringaa4 commented on presentation/src/main/java/com/example/dms_android/feature/register/screen/school/ConfirmSchoolScreen.kt
> +                //TODO: 여기서 schoolQuestion띄워주는 코드 작성하는게 맞는거지?
띄워주는 코드를 Composable로 뺀다음에 그 함수 호출하면 되잖아요. 람다 안에서는 Composable함수 사용 불가능 하니까 함수형 프로그래밍으로 함수를 변수로 선언해서

2022-10-31 03:32 UTC, aahspringaa4 commented on presentation/src/main/java/com/example/dms_android/feature/register/screen/school/ConfirmSchoolScreen.kt
> +                    duration = SnackbarDuration.Short
여기 Trailing Comma 다 빠졌어요.

2022-10-31 03:32 UTC, aahspringaa4 commented on presentation/src/main/java/com/example/dms_android/feature/register/screen/school/ConfirmSchoolScreen.kt
> +                    duration = SnackbarDuration.Short
여기도

2022-10-31 03:32 UTC, aahspringaa4 commented on presentation/src/main/java/com/example/dms_android/feature/register/screen/school/ConfirmSchoolScreen.kt
> +                    duration = SnackbarDuration.Short
여기도

2022-10-31 03:32 UTC, aahspringaa4 commented on presentation/src/main/java/com/example/dms_android/feature/register/screen/school/ConfirmSchoolScreen.kt
> +                    duration = SnackbarDuration.Short
여기도

2022-10-31 03:32 UTC, aahspringaa4 commented on presentation/src/main/java/com/example/dms_android/feature/register/screen/school/ConfirmSchoolScreen.kt
> +                    duration = SnackbarDuration.Short
여기도

2022-10-31 03:32 UTC, aahspringaa4 commented on presentation/src/main/java/com/example/dms_android/feature/register/screen/school/ConfirmSchoolScreen.kt
> +            else -> {
이렇게 두지 말고 Todo 라도 박아놓으세요

2022-10-31 03:32 UTC, aahspringaa4 commented on presentation/src/main/java/com/example/dms_android/feature/register/screen/school/ConfirmSchoolScreen.kt
> +    val notFoundComment = stringResource(id = R.string.LoginNotFound)
여기도 Login 사용하시면 안되는데 똑바로 안보죠. 예외처리가 되는 이유가 다 다른데

2022-10-31 03:32 UTC, aahspringaa4 commented on presentation/src/main/java/com/example/dms_android/feature/register/screen/school/ConfirmSchoolScreen.kt
> +fun HandleViewEffectTwo(
HandleViewEffectTwo네이밍은 진짜개별로에요. Api에 따라서 HandleViewEffect네이밍을 하던가요

2022-10-31 03:32 UTC, aahspringaa4 commented on presentation/src/main/java/com/example/dms_android/feature/register/screen/school/ConfirmSchoolScreen.kt
> +                    duration = SnackbarDuration.Short
여기도 Trailing Comma

2022-10-31 03:32 UTC, aahspringaa4 commented on presentation/src/main/java/com/example/dms_android/feature/register/screen/school/ConfirmSchoolScreen.kt
> +                    duration = SnackbarDuration.Short
여기도

2022-10-31 03:32 UTC, aahspringaa4 commented on presentation/src/main/java/com/example/dms_android/feature/register/screen/school/ConfirmSchoolScreen.kt
> +                    duration = SnackbarDuration.Short
여기도

2022-10-31 03:32 UTC, aahspringaa4 commented on presentation/src/main/java/com/example/dms_android/feature/register/screen/school/ConfirmSchoolScreen.kt
> +                    duration = SnackbarDuration.Short
여기도

2022-10-31 03:32 UTC, aahspringaa4 commented on presentation/src/main/java/com/example/dms_android/feature/register/screen/school/ConfirmSchoolScreen.kt
> +                    duration = SnackbarDuration.Short
여기도

2022-10-31 03:32 UTC, aahspringaa4 commented on presentation/src/main/java/com/example/dms_android/feature/register/screen/school/ConfirmSchoolScreen.kt
> +                    duration = SnackbarDuration.Short
여기도

2022-10-31 03:32 UTC, aahspringaa4 commented on presentation/src/main/java/com/example/dms_android/feature/register/screen/school/ConfirmSchoolScreen.kt
> +                onActive = true
onActice말고 따로 실행되어야하는 함수를 호출 해야한다고 Todo를 박던지 하세요.

2022-10-31 03:32 UTC, aahspringaa4 commented on presentation/src/main/java/com/example/dms_android/feature/register/screen/school/ConfirmSchoolScreen.kt
> +                onActive = false
여기도 Todo 라도 박으세요. 아무것도 안할 순 없잖아요. 예외처리를 했는데

2022-10-31 03:32 UTC, aahspringaa4 commented on presentation/src/main/java/com/example/dms_android/feature/register/screen/school/SchoolCertificationCodeScreen.kt
> +private var onBtnActive = false
변수를 함수 밖에서 선언하는게 코드적으로 말이 되나요?

2022-10-31 03:32 UTC, aahspringaa4 commented on presentation/src/main/java/com/example/dms_android/feature/register/screen/school/SchoolCertificationCodeScreen.kt
> +        effect = examineSchoolCodeViewModel.examineSchoolCodeEvent
TrailingComma 빠졌어요

2022-10-31 03:32 UTC, aahspringaa4 commented on presentation/src/main/java/com/example/dms_android/feature/register/screen/school/SchoolCertificationCodeScreen.kt
> +        mutableStateOf(false)
다른곳은 띄어쓰기 안해줬으면서 여기는 왜 띄어쓰기가 되어있을까요. 다른곳도 띄우던지 여기를 붙이던지 수정해주세요,

2022-10-31 03:32 UTC, aahspringaa4 commented on presentation/src/main/java/com/example/dms_android/feature/register/screen/school/SchoolCertificationCodeScreen.kt
> +    var otpValue by remember { mutableStateOf("") }
이것도 stringResource 사용하시는게 좋을것같아요. 아무리 초기화라도 코드 통일성때문에

2022-10-31 03:32 UTC, aahspringaa4 commented on presentation/src/main/java/com/example/dms_android/feature/register/screen/school/SchoolCertificationCodeScreen.kt
> +            .background(Color.White)
디자인 시스템 활용 안하세요"?

2022-10-31 03:32 UTC, aahspringaa4 commented on presentation/src/main/java/com/example/dms_android/feature/register/screen/school/ConfirmSchoolScreen.kt
> +            .background(Color.White)
디자인 시스템 활용 안하세요?

2022-10-31 03:32 UTC, aahspringaa4 commented on presentation/src/main/java/com/example/dms_android/feature/register/screen/school/SchoolCertificationCodeScreen.kt
> +                .padding(top = 77.dp)
padding을 두번쓰는건 뭔 경우에요.. 같은 padding안에서 값을 주셔야죠

2022-10-31 03:32 UTC, aahspringaa4 commented on presentation/src/main/java/com/example/dms_android/feature/register/screen/school/SchoolCertificationCodeScreen.kt
> +                modifier = Modifier.size(49.dp),
modifier에서는 인자값 줄바꾸는게 저희 코드 스타일이에요. 줄 바꿔주세요.

2022-10-31 03:32 UTC, aahspringaa4 commented on presentation/src/main/java/com/example/dms_android/feature/register/screen/school/SchoolCertificationCodeScreen.kt
> +            Body4(text = stringResource(R.string.SchoolVerificationCode), color = DormColor.Gray600)
여기도 줄 바꿔주세요. 인자값이 2개 이상이니까, 그리고 Trailing Comma도 빠졌습니다,

2022-10-31 03:32 UTC, aahspringaa4 commented on presentation/src/main/java/com/example/dms_android/feature/register/screen/school/SchoolCertificationCodeScreen.kt
> +                passwordChar = "⚫",
stringResource사용해주세요.

2022-10-31 03:32 UTC, aahspringaa4 commented on presentation/src/main/java/com/example/dms_android/feature/register/screen/school/SchoolCertificationCodeScreen.kt
> +                horizontalAlignment = Alignment.CenterHorizontally
Trailing Comma

2022-10-31 03:32 UTC, aahspringaa4 commented on presentation/src/main/java/com/example/dms_android/feature/register/screen/school/SchoolCertificationCodeScreen.kt
> +    val unAuthorizedComment = stringResource(id = R.string.LoginUnAuthorized)
여기도 login exception사용하시지 마세요. 제가 편하게 구분하라고 앞에 로그인도 붙여드렸는데..

2022-10-31 03:32 UTC, aahspringaa4 commented on presentation/src/main/java/com/example/dms_android/feature/register/screen/school/SchoolCertificationCodeScreen.kt
> +                        }
TrailingComma

2022-10-31 03:32 UTC, aahspringaa4 commented on presentation/src/main/java/com/example/dms_android/feature/register/screen/school/SchoolCertificationCodeScreen.kt
> +                            //TODO : 다음페이지로 넘어가기
주석 달지 말고 Todo를 써주세요.

2022-10-31 03:32 UTC, aahspringaa4 commented on presentation/src/main/java/com/example/dms_android/feature/register/screen/school/SchoolCertificationCodeScreen.kt
> +                onBtnActive = true
여기도 todo써주세요.

2022-10-31 03:32 UTC, aahspringaa4 commented on presentation/src/main/java/com/example/dms_android/feature/register/screen/school/SchoolCertificationCodeScreen.kt
> +    val tooManyRequestComment = stringResource(id = R.string.TooManyRequest)
명세서에 보니까 NotFound도 예외처리 되어있는데 왜 여긴 Notfound 예외처리 안되어있나요?

2022-10-31 03:32 UTC, aahspringaa4 commented on presentation/src/main/java/com/example/dms_android/feature/register/screen/school/SchoolCertificationCodeScreen.kt
> +                    duration = SnackbarDuration.Short
Trailing Comma요

2022-10-31 03:32 UTC, aahspringaa4 commented on presentation/src/main/java/com/example/dms_android/feature/register/screen/school/SchoolCertificationCodeScreen.kt
> +                    duration = SnackbarDuration.Short
여기도

2022-10-31 03:32 UTC, aahspringaa4 commented on presentation/src/main/java/com/example/dms_android/feature/register/screen/school/SchoolCertificationCodeScreen.kt
> +                    duration = SnackbarDuration.Short
여기도

2022-10-31 03:32 UTC, aahspringaa4 commented on presentation/src/main/java/com/example/dms_android/feature/register/screen/school/SchoolCertificationCodeScreen.kt
> +                    duration = SnackbarDuration.Short
여기도

2022-10-31 03:32 UTC, aahspringaa4 commented on presentation/src/main/java/com/example/dms_android/feature/register/screen/school/SchoolCertificationCodeScreen.kt
> +                    duration = SnackbarDuration.Short
여기도

2022-10-31 03:32 UTC, aahspringaa4 commented on presentation/src/main/java/com/example/dms_android/feature/register/screen/school/SchoolCertificationCodeScreen.kt
> +                onBtnActive = false
여기도 Todo 박으세요

2022-10-31 03:32 UTC, aahspringaa4 commented on presentation/src/main/java/com/example/dms_android/viewmodel/auth/register/school/CompareSchoolAnswerViewModel.kt
> +            //schoolId 전달받기
이런 주석은 커밋하시면 안되요.

2022-10-31 03:32 UTC, aahspringaa4 commented on presentation/src/main/java/com/example/dms_android/viewmodel/auth/register/school/ExamineSchoolCodeViewModel.kt
> +
바디 빈공간으로 두지 말고 Todo 라도 박으세요.

2022-10-31 03:32 UTC, aahspringaa4 commented on presentation/src/main/java/com/example/dms_android/viewmodel/auth/register/school/CompareSchoolAnswerViewModel.kt
> +
바디 빈공간으로 두지 말고 Todo 라도 박으세요.

2022-10-31 03:32 UTC, aahspringaa4 commented on presentation/src/main/java/com/example/dms_android/viewmodel/auth/register/school/CompareSchoolAnswerViewModel.kt
> +    private lateinit var schoolId : UUID
이런식으로 사용하면 초기화 안된 함수라고 컴파일 에러 날것같은데 실행 해보시고 올리시는건가요?

2022-10-31 03:33 UTC, aahspringaa4 commented
그리고 앞으로는 이렇게 이슈단위 크게 잡지 마세요. 이렇게 하면 앞으로 리뷰 못합니다.

2022-10-31 03:49 UTC, Leesin0222 commented on presentation/src/main/java/com/example/dms_android/feature/register/screen/school/ConfirmSchoolScreen.kt
> +    var replyValue by remember { mutableStateOf("") }
> 뷰 작업 끝난거 사진 형태로 PR에 같이 올려주세요. 그리고 코드적으로 약간 이상한 부분이 많은데 다 컴파일 해보고 올리시는거 맞죠?

 구현가능한 부분만 올린거라 pr label에 논의 필요랑 보류 중 걸어놨던 상태입니다.

2022-11-04 02:59 UTC, limsaehyun commented on presentation/src/main/java/com/example/dms_android/feature/register/event/school/CompareSchoolAnswerEvent.kt
> +    object CompareSchoolAnswerSuccess : CompareSchoolAnswerEvent()
항상 보면서 느끼는건데,
중복되는 Exception들을 계속해서 만들어줘야 할까요?
뭔가 boilerPlate 같아요
개선점을 찾으면 좋을 것 같습니다

2022-11-04 02:59 UTC, limsaehyun commented on presentation/src/main/java/com/example/dms_android/feature/register/screen/school/SchoolCertificationCodeScreen.kt
> +private var onBtnActive = false
@aahspringaa4 추후에 업데이트가 일어날 때 가독성을 위해서 빼신 것으로 보여요

2022-11-04 05:01 UTC, Leesin0222 commented on presentation/src/main/java/com/example/dms_android/feature/register/event/school/CompareSchoolAnswerEvent.kt
> +    object CompareSchoolAnswerSuccess : CompareSchoolAnswerEvent()
음 알겠습니다. 개선할 수 있는 방안을 생각해보겠습니다.

2022-11-04 09:46 UTC, merged